name: infinity_skill_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flame: ^1.38.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.15.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  flutter_gen_runner: ^5.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/parallax/
    - assets/sprites/effects/fire/
    - assets/sprites/effects/ice/
    - assets/sprites/effects/wind/
    - assets/sprites/effects/thunder/
    - assets/sprites/effects/water/
    - assets/sprites/effects/hit/
    - assets/sprites/effects/buff1/
    - assets/sprites/buff/
    - assets/sprites/characters/wizzard/
    - assets/sprites/characters/knight/
    - assets/sprites/monster/slime/
    - assets/sprites/monster/golem/
    - assets/sprites/monster/flying_demon/
    - assets/icons/
    - assets/icons/alchemy/
    - assets/icons/arachnid/
    - assets/icons/arcane/
    - assets/icons/blood/
    - assets/icons/consumable/
    - assets/icons/crafting/
    - assets/icons/danger/
    - assets/icons/dark/
    - assets/icons/earth/
    - assets/icons/equipment/
    - assets/icons/fire/
    - assets/icons/holy/
    - assets/icons/ice/
    - assets/icons/lightning/
    - assets/icons/loot/
    - assets/icons/monster/
    - assets/icons/nature/
    - assets/icons/physical/
    - assets/icons/poison/
    - assets/icons/psionic/
    - assets/icons/ranged/
    - assets/icons/sound/
    - assets/icons/stats/
    - assets/icons/status/
    - assets/icons/stealth/
    - assets/icons/symbol/
    - assets/icons/terrain/
    - assets/icons/time/
    - assets/icons/ui/
    - assets/icons/utility/
    - assets/icons/water/
    - assets/icons/weather/
    - assets/icons/wind/
    - assets/icons/world/
