// GENERATED CODE - DO NOT MODIFY BY HAND
import 'upgrade_data.dart';

enum ActivationLevel {
  hidden,
  discovered,
  revealed,
  available,
  leveled,
  maxed,
}

enum Tag {
  core,
  burn,
  lightning,
  crit,
  arrow,
  slow,
  economy,
  coin_cannon,
  explosive,
  misc,
  pool,
  poison,
  vulnerable,
  charge,
  combust,
}

enum Keyword {
  combustion,
  vulnerable,
  critical_hit,
  artifact_unlock,
  charge,
  pool,
  poison,
  required_completed_level,
}

enum ValueFormat {
  number,
  percentage,
  percentage_decimals,
}

enum Upgrade {
  arrow_tower_unlock,
  slow_tower_unlock,
  starting_gems,
  starting_gems_2,
  arrow_tower_damage,
  arrow_tower_fire_rate,
  arrow_tower_fire_rate_2,
  arrow_tower_fire_rate_3,
  arrow_tower_crit_chance,
  arrow_tower_crit_damage,
  arrow_tower_multicrit,
  arrow_tower_multicrit_2,
  arrow_tower_multicrit_combustion,
  arrow_tower_build_cost_damage_multiplier,
  arrow_tower_upgrade_cost_damage_multiplier,
  arrow_tower_poison,
  arrow_tower_more_poison,
  arrow_tower_poison_on_shields,
  arrow_tower_poison_pool,
  arrow_tower_fire_rate_increase_damage_decrease,
  arrow_tower_leveling_fire_rate_2,
  arrow_tower_crit_poison,
  arrow_tower_poison_vulnerable,
  arrow_tower_poison_charge_add_stacks,
  arrow_tower_heavy,
  arrow_tower_range,
  arrow_tower_crit_chance_2,
  arrow_tower_crit_damage_2,
  arrow_tower_multicrit_leveled,
  arrow_tower_damage_at_range,
  arrow_tower_unharmed_crit_chance,
  arrow_tower_damage_2,
  arrow_tower_damage_3,
  arrow_tower_pierce_shield,
  arrow_tower_disable,
  status_effect_count_increase_damage,
  status_effect_count_increase_damage_extra,
  tower_upgrade_unlock,
  tower_demolish_unlock,
  gem_convert,
  gem_drops,
  basic_token_drops,
  gem_cannon,
  early_spawn,
  auto_start_wave,
  arrow_tower_multishot,
  arrow_tower_multishot_increased_damage,
  arrow_tower_multishot_triple_when_leveled,
  targetting,
  gem_shot,
  early_spawn_gem_bonus,
  early_spawn_charge,
  early_spawn_charge_extra,
  accelerated_enemy_basic_token_bonus,
  time_challenge_unlock,
  slow_tower_damage_link,
  slow_tower_damage_link_increase,
  slow_tower_damage_link_share_sources,
  targetting_auto,
  vulnerable_damage_multiplier,
  slow_amount,
  slow_vulnerable,
  slow_tower_fire_rate,
  slow_duration,
  slow_duration_2,
  slow_tower_charge_buff,
  slow_damage_bonus,
  charge_amount,
  charge_amount_2,
  charge_damage_bonus,
  charge_damage_stacking,
  slow_zone,
  explosive_grunts_chance,
  explosive_runners_chance,
  explosive_damage,
  explosive_damage_2,
  explosive_grunts,
  explosive_bosses,
  explosive_bosses_2,
  explosive_elites,
  explosive_elites_2,
  explosion_range_increase,
  explosion_tower_charge,
  explosion_tower_charge_extra,
  explosion_chance_to_create_pool,
  explosion_fireball,
  explosion_fireball_chance,
  explosion_fireball_burn_damage,
  explosion_fireball_explosion_damage,
  explosion_fireball_double_chance,
  tower_upgrade_auto,
  gem_cannon_damage,
  gem_cannon_damage_extra,
  gem_cannon_fire_rate,
  gem_cannon_shot_reimbursement_chance,
  gem_cannon_crit_chance,
  auto_collect_gems,
  gem_cannon_damage_expensive,
  gem_cannon_damage_expensive_extra,
  gem_cannon_auto_shoot,
  demolish_unrestricted,
  demolish_refund_amount,
  demolish_refund_amount_2,
  demolish_explosion,
  core_health,
  core_health_2,
  core_health_3,
  core_lost_health_increase_damage,
  core_burn_pulse,
  core_burn_pulse_damage,
  core_burn_pulse_range,
  core_burn_combust,
  core_killed_enemy_reward,
  core_killed_enemy_reward_coins,
  core_apply_wave_burn,
  core_charge,
  core_charge_extra,
  core_heal,
  core_heal_extra,
  burn_damage,
  burn_damage_fire_tower,
  burn_damage_extra,
  burn_damage_extra_for_reduced_tick_rate,
  burn_ticks,
  burn_ticks_extra,
  burn_crit,
  burn_stacking_damage,
  burn_spreading,
  burn_spread_chance,
  burn_spread_to_burning,
  burn_concentration,
  fire_tower_unlock,
  burn_crit_add_tick,
  burn_tick_rate,
  burn_tick_crit_chance,
  burn_pool_apply_burn,
  burn_pool_apply_burn_extra,
  burn_tick_rate_accelerated_enemies,
  burn_tick_rate_accelerated_enemies_extra,
  lightning_tower_unlock,
  lightning_tower_spread_status,
  lightning_tower_jumps,
  lightning_tower_extra_jumps,
  lightning_tower_damage,
  lightning_tower_damage_extra,
  lightning_tower_speed,
  lightning_tower_extra_speed,
  lightning_tower_crit_chance,
  lightning_tower_crit_charge,
  lightning_tower_charge_extra_jumps,
  lightning_tower_overkill_damage,
  lightning_tower_overkill_damage_extra,
  lightning_tower_overkill_retrigger_chance,
  lightning_tower_jump_damage_reduction,
  lightning_tower_chance_to_jump_again,
  lightning_tower_chance_to_jump_again_extra,
  lightning_tower_apply_shock,
  lightning_tower_shock_stun_duration,
  lightning_tower_shock_stun_duration_extra,
  lightning_tower_stun_increase_damage,
  lightning_tower_stun_increase_damage_extra,
  lightning_tower_discharge_combust,
  lightning_tower_jump_range,
  level_challenge_unlock,
  increased_vulnerable_damage_undamaged_enemies,
  boss_defeat_partial_token,
  boss_damage_taken_basic_token_increase,
  economy_damage_increase_by_coins,
  economy_gem_interest,
  economy_enemy_defeat_upgrade_discount,
  economy_uncapped_levels,
  bank_tower_unlock,
  bank_tower_chance_to_spawn_coin,
  bank_tower_number_coins,
  bank_tower_add_vulnerable,
  bank_tower_vulnerable_duration,
  bank_tower_pool,
  bank_tower_tokens,
  bank_tower_basic_tokens_multiplier,
  bank_tower_damage,
  bank_tower_damage_extra,
  bank_tower_accelerated_enemies,
  artifacts_unlock,
  fire_artifact_unlock,
  light_artifact_unlock,
  earth_artifact_unlock,
  wind_artifact_unlock,
  ice_artifact_unlock,
  fire_artifact_2_unlock,
  light_artifact_2_unlock,
  earth_artifact_2_unlock,
  wind_artifact_2_unlock,
  ice_artifact_2_unlock,
  build_presets_unlock,
}

final Map<Upgrade, UpgradeData> upgradesMap = {
  Upgrade.arrow_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'basic',
    iconPath: 'assets/sprites/arrow_tower_icon.png',
    activationLevel: ActivationLevel.available,
    tags: [Tag.arrow],
  ),
  Upgrade.starting_gems: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [3, 10, 20, 40, 100][l],
    costToken: 'basic',
    value: (int l) => l * 5,
    iconPath: 'assets/sprites/starting_gems_icon.png',
    dependency: Upgrade.arrow_tower_unlock,
    tags: [Tag.economy],
  ),
  Upgrade.starting_gems_2: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 200, 250][l],
    costToken: 'advanced',
    value: (int l) => l * 10,
    iconPath: 'assets/sprites/starting_gems_icon.png',
    dependency: Upgrade.gem_convert,
    tags: [Tag.economy],
  ),
  Upgrade.gem_convert: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [10, 100, 200, 400, 800][l],
    costToken: 'basic',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/gem_convert_icon.png',
    dependency: Upgrade.gem_shot,
    tags: [Tag.economy],
  ),
  Upgrade.core_health: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [5, 30, 75, 150, 300][l],
    costToken: 'basic',
    value: (int l) => l,
    iconPath: 'assets/sprites/health_icon.png',
    dependency: Upgrade.starting_gems,
    tags: [Tag.core],
  ),
  Upgrade.core_health_2: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/health_icon.png',
    dependency: Upgrade.core_health,
    value: (int l) => l * 10,
    tags: [Tag.core],
  ),
  Upgrade.core_health_3: UpgradeData(
    maxLevel: 4,
    cost: (int _l) => [50, 100, 150, 200][_l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/health_icon.png',
    dependency: Upgrade.core_killed_enemy_reward_coins,
    value: (int l) => l * 3,
    tags: [Tag.core],
  ),
  Upgrade.core_burn_pulse: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/burn_pulse_icon.png',
    dependency: Upgrade.core_health_3,
    data: {
      'pulse_cooldown': 3,
    },
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_lost_health_increase_damage: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 250, 600][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/lost_health_icon.png',
    dependency: Upgrade.core_health,
    value: (int l) => l * 0.0025,
    valueFormat: ValueFormat.percentage_decimals,
    tags: [Tag.core],
  ),
  Upgrade.core_burn_pulse_damage: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 200, 250][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/burn_pulse_damage_icon.png',
    dependency: Upgrade.core_burn_pulse,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.core, Tag.burn],
  ),

  Upgrade.core_burn_pulse_range: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 200, 250][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/burn_pulse_range_icon.png',
    dependency: Upgrade.core_burn_pulse,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_burn_combust: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/core_combust_icon.png',
    dependency: Upgrade.core_burn_pulse_damage,
    keywords: [Keyword.combustion],
    value: (int l) => l * 10,
    data: {
      'combust_ticks': 15,
    },
    tags: [Tag.core, Tag.burn, Tag.combust],
  ),
  Upgrade.core_killed_enemy_reward: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 100,
    costToken: 'basic',
    iconPath: 'assets/sprites/core_killed_enemy_reward_icon.png',
    dependency: Upgrade.core_health,
    tags: [Tag.core],
  ),
  Upgrade.core_killed_enemy_reward_coins: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [100, 400][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/core_killed_enemy_coin_reward_icon.png',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.core_killed_enemy_reward,
    tags: [Tag.core],
  ),
  Upgrade.core_apply_wave_burn: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/core_wave_burn_icon.png',
    dependency: Upgrade.core_burn_pulse_range,
    value: (int l) => l,
    data: {
      'boss_damage': {
        'value': 0.0025,
        'format': ValueFormat.percentage_decimals,
      },
      'regular_damage': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_charge: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 200, 250][l],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    iconPath: 'assets/sprites/core_charge_icon.png',
    dependency: Upgrade.core_burn_pulse_damage,
    tags: [Tag.core, Tag.charge],
    keywords: [Keyword.charge],
  ),
  Upgrade.core_charge_extra: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    value: (int l) => l * 0.25,
    dependency: Upgrade.core_charge,
    iconPath: 'assets/sprites/core_charge_icon.png',
    tags: [Tag.core, Tag.charge],
  ),
  Upgrade.core_heal: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/heal_icon.png',
    dependency: Upgrade.core_lost_health_increase_damage,
    value: (int l) => l * 3,
    data: {
      'increase': {
        'value': 1,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.core_heal_extra: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [50, 150][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/heal_more_icon.png',
    dependency: Upgrade.core_heal,
    value: (int l) => l,
  ),
  Upgrade.gem_drops: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l,
    iconPath: 'assets/sprites/gem_drops_icon.png',
    dependency: Upgrade.boss_damage_taken_basic_token_increase,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.economy],
  ),
  Upgrade.arrow_tower_damage: UpgradeData(
    maxLevel: 10,
    cost: (int l) => [3, 5, 15, 50, 150, 500, 800, 1250, 1750, 2500][l],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_unlock,
    value: (int l) => l * 5,
    iconPath: 'assets/sprites/arrow_damage_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_build_cost_damage_multiplier: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 250,
    costToken: 'advanced',
    dependency: Upgrade.vulnerable_damage_multiplier,
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    data: {
      'build_cost_multiplier': {
        'value': (int l) => 0.5 * l,
        'format': ValueFormat.percentage,
      },
    },
    iconPath: 'assets/sprites/arrow_tower_build_cost_damage.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_upgrade_cost_damage_multiplier: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 250,
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_build_cost_damage_multiplier,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    data: {
      'upgrade_cost_multiplier': {
        'value': (int l) => 0.5 * l,
        'format': ValueFormat.percentage,
      },
    },
    iconPath: 'assets/sprites/arrow_tower_build_cost_damage.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_fire_rate: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [3, 50][l],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_unlock,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/tower_fire_rate_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_fire_rate_2: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    dependency: Upgrade.arrow_tower_fire_rate,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/tower_fire_rate_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_fire_rate_3: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [1, 2][l],
    costToken: 'time',
    dependency: Upgrade.arrow_tower_range,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/tower_fire_rate_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_crit_chance: UpgradeData(
    maxLevel: 3,
    iconPath: 'assets/sprites/crit_chance_icon.png',
    cost: (int l) => [25, 100, 400][l],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_damage,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    keywords: [Keyword.critical_hit],
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_crit_damage: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/crit_damage_icon.png',
    cost: (int l) => [50, 100, 150, 250, 400][l],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_crit_chance,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_multicrit: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_icon.png',
    cost: (int _l) => 1,
    costToken: 'star',
    dependency: Upgrade.arrow_tower_crit_chance,
    value: (int l) => l,
    data: {
      'damage': {
        'value': 1.0,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_multicrit_combustion: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_combust_icon.png',
    cost: (int _l) => 250,
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_multicrit,
    value: (int l) => l,
    data: {
      'combust_ticks': 3,
    },
    keywords: [Keyword.combustion],
    tags: [Tag.arrow, Tag.crit, Tag.combust],
  ),
  Upgrade.arrow_tower_multicrit_2: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_icon.png',
    cost: (int _l) => 50,
    costToken: 'advanced',
    data: {
      'level_required': 3,
    },
    dependency: Upgrade.arrow_tower_multicrit,
    value: (int l) => l,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_heavy: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_heavy_icon.png',
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_multicrit_2,
    data: {
      'reduced_fire_rate': {
        'value': 0.8,
        'format': ValueFormat.percentage,
      },
      'increased_damage': {
        'value': 7.0,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_range: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/arrow_tower_range_icon.png',
    cost: (int l) => [50, 100, 250, 500, 750][l],
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_heavy,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_crit_chance_2: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/crit_chance_icon.png',
    cost: (int l) => [50, 100, 250, 500, 750][l],
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_heavy,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_crit_damage_2: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/crit_damage_icon.png',
    cost: (int l) => [50, 100, 250, 500, 750][l],
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_crit_chance_2,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_multicrit_leveled: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_icon.png',
    cost: (int _l) => 1,
    value: (int l) => l,
    costToken: 'challenge',
    data: {
      'level_required': 5,
    },
    dependency: Upgrade.arrow_tower_crit_chance_2,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_damage_at_range: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_range_damage_icon.png',
    cost: (int _l) => 500,
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_range,
    value: (int l) => l * 0.025,
    valueFormat: ValueFormat.percentage_decimals,
    data: {
      'per_range_unit': 100,
    },
    tags: [Tag.arrow],
  ),

  Upgrade.arrow_tower_unharmed_crit_chance: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_target_highest_health_icon.png',
    cost: (int _l) => 1,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    costToken: 'challenge',
    dependency: Upgrade.arrow_tower_damage_3,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_damage_2: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/arrow_damage_icon.png',
    cost: (int _l) => [50, 250, 500, 750, 1000][_l],
    costToken: 'advanced',
    value: (int l) => l * 5,
    dependency: Upgrade.vulnerable_damage_multiplier,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_damage_3: UpgradeData(
    maxLevel: 3,
    iconPath: 'assets/sprites/arrow_damage_icon.png',
    cost: (int l) => [100, 200, 400][l],
    costToken: 'advanced',
    value: (int l) => l * 5,
    dependency: Upgrade.arrow_tower_heavy,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_pierce_shield: UpgradeData(
    maxLevel: 2,
    iconPath: 'assets/sprites/arrow_tower_shielded_icon.png',
    cost: (int l) => [100, 250][l],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.arrow_tower_heavy,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_disable: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_disable_icon.png',
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_pierce_shield,
    tags: [Tag.arrow],
    data: {
      'key_action_string': 'SHIFT',
    },
  ),
  Upgrade.slow_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/slow_tower_icon.png',
    dependency: Upgrade.arrow_tower_unlock,
    tags: [Tag.slow],
  ),
  Upgrade.tower_upgrade_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 10,
    costToken: 'basic',
    isMilestone: true,
    dependency: Upgrade.arrow_tower_unlock,
    iconPath: 'assets/sprites/upgrade_icon.png',
    tags: [Tag.core],
  ),
  Upgrade.tower_demolish_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 100,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/demolish_icon.png',
    dependency: Upgrade.tower_upgrade_unlock,
    data: {
      'full_refund': {
        'value': 1.0,
        'format': ValueFormat.percentage,
      },
      'partial_refund': {
        'value': 0.5,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.misc],
  ),
  Upgrade.early_spawn: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 250,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/early_spawn_icon.png',
    value: (int l) => l,
    dependency: Upgrade.tower_upgrade_unlock,
    data: {
      'gem': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.economy],
  ),
  Upgrade.early_spawn_gem_bonus: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 200, 400, 800][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/early_spawn_gem_bonus_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.basic_token_drops,
    tags: [Tag.economy],
  ),
  Upgrade.early_spawn_charge: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 200, 250][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/early_spawn_charge_icon.png',
    value: (int l) => l * 0.5,
    dependency: Upgrade.early_spawn_gem_bonus,
    tags: [Tag.charge],
    keywords: [Keyword.charge],
  ),
  Upgrade.early_spawn_charge_extra: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/early_spawn_charge_icon.png',
    value: (int l) => l * 1.5,
    dependency: Upgrade.early_spawn_charge,
    tags: [Tag.charge],
    keywords: [Keyword.charge],
  ),
  Upgrade.auto_start_wave: UpgradeData(
    maxLevel: 1,
    isMilestone: true,
    cost: (int _l) => 3500,
    costToken: 'basic',
    iconPath: 'assets/sprites/auto_start_wave_icon.png',
    value: (int l) => l,
    dependency: Upgrade.tower_upgrade_auto,
    tags: [Tag.misc],
  ),
  Upgrade.accelerated_enemy_basic_token_bonus: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [100, 200][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/early_spawn_basic_token_bonus_icon.png',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.early_spawn_gem_bonus,
    tags: [Tag.economy],
  ),
  Upgrade.time_challenge_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 500,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/time_challenge_icon.png',
    value: (int l) => l,
    dependency: Upgrade.early_spawn,
    tags: [Tag.core],
  ),
  Upgrade.tower_upgrade_auto: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1250,
    isMilestone: true,
    costToken: 'basic',
    iconPath: 'assets/sprites/auto_upgrade_icon.png',
    dependency: Upgrade.tower_upgrade_unlock,
    tags: [Tag.core],
  ),
  Upgrade.level_challenge_unlock: UpgradeData(
    maxLevel: 1,
    isMilestone: true,
    cost: (int _l) => 2500,
    value: (int l) => l,
    costToken: 'basic',
    iconPath: 'assets/sprites/level_challenge_icon.png',
    dependency: Upgrade.time_challenge_unlock,
    tags: [Tag.core],
  ),
  Upgrade.basic_token_drops: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [15, 30, 50, 75, 115][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/green_token_drops_icon.png',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.starting_gems,
    tags: [Tag.economy],
  ),
  Upgrade.gem_cannon: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l,
    iconPath: 'assets/sprites/gem_cannon_icon.png',
    dependency: Upgrade.starting_gems,
    data: {
      'damage_range': '10-20',
    },
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_auto_shoot: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    defaultUnlockedOnMobile: true,
    iconPath: 'assets/sprites/auto_shoot_icon.png',
    value: (int l) => l,
    dependency: Upgrade.gem_cannon,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.arrow_tower_multishot: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/multishot_icon.png',
    dependency: Upgrade.arrow_tower_fire_rate,
    value: (int l) => l,
    data: {
      'damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_multishot_triple_when_leveled: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 2,
    costToken: 'challenge',
    iconPath: 'assets/sprites/tripleshot_icon.png',
    dependency: Upgrade.arrow_tower_poison_vulnerable,
    value: (int l) => l,
    tags: [Tag.arrow, Tag.poison],
    data: {
      'level_required': {
        'value': 5,
        'format': ValueFormat.number,
      },
      'damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.arrow_tower_multishot_increased_damage: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [100, 300, 500][_l],
    costToken: 'basic',
    iconPath: 'assets/sprites/multishot_damage_icon.png',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.arrow_tower_multishot,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_poison: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/poison_icon.png',
    value: (int _l) => 2,
    data: {'reduced_effectiveness_after': 100},
    dependency: Upgrade.arrow_tower_fire_rate_increase_damage_decrease,
    keywords: [Keyword.poison],
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_more_poison: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [100, 250, 500][_l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/poison_stacks_icon.png',
    value: (int l) => 1 * l,
    dependency: Upgrade.arrow_tower_poison,
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_poison_on_shields: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 300,
    costToken: 'advanced',
    iconPath: 'assets/sprites/shielded_poison_icon.png',
    dependency: Upgrade.arrow_tower_more_poison,
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_poison_pool: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [100, 200, 400][_l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/poison_pool_icon.png',
    value: (int l) => 5 * l,
    dependency: Upgrade.arrow_tower_more_poison,
    tags: [Tag.poison, Tag.pool],
  ),
  Upgrade.arrow_tower_crit_poison: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [50, 100, 200][_l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/crit_poison_icon.png',
    value: (int l) => 0.03 * l,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.arrow_tower_more_poison,
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_poison_vulnerable: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => [150, 300][_l],
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/vulnerable_poison_icon.png',
    dependency: Upgrade.arrow_tower_crit_poison,
    tags: [Tag.poison, Tag.vulnerable],
  ),
  Upgrade.arrow_tower_poison_charge_add_stacks: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/charge_poison_icon.png',
    dependency: Upgrade.arrow_tower_crit_poison,
    value: (int l) => l,
    tags: [Tag.poison, Tag.charge],
    data: {
      'add_stacks': {'value': (int _l) => 10, 'format': ValueFormat.number},
    },
  ),
  Upgrade.arrow_tower_fire_rate_increase_damage_decrease: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 250, 500][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/light_arrows_icon.png',
    dependency: Upgrade.arrow_tower_multishot,
    tags: [Tag.arrow],
    value: (int l) => 0.1 * l,
    valueFormat: ValueFormat.percentage,
    data: {
      'decrease_damage': {
        'value': (int l) => 0.05 * l,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.arrow_tower_leveling_fire_rate_2: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/light_arrows_icon.png',
    dependency: Upgrade.arrow_tower_crit_poison,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow],
    data: {
      'decrease_damage': {
        'value': (int l) => 0.1 * l,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.explosive_grunts: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/explosion_icon.png',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_damage,
    data: {
      'base_chance': 0.2,
      'chance': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
      'damage': {
        'value': 0.15,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.explosive],
  ),
  Upgrade.targetting: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 20,
    costToken: 'basic',
    iconPath: 'assets/sprites/targetting_icon.png',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_damage,
    data: {
      'vulnerable_damage': ((VulnerableStatus.BASE_DAMAGE_MULTIPLIER - 1.0) * 100).round(),
    },
    keywords: [Keyword.vulnerable],
    tags: [Tag.arrow, Tag.vulnerable],
  ),
  Upgrade.vulnerable_damage_multiplier: UpgradeData(
    maxLevel: 6,
    cost: (int l) => [25, 50, 100, 200, 400, 800][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/vulnerability_effect_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.targetting,
    tags: [Tag.arrow, Tag.vulnerable],
  ),
  Upgrade.targetting_auto: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 50,
    costToken: 'basic',
    iconPath: 'assets/sprites/targetting_damage_icon.png',
    value: (int l) => l,
    dependency: Upgrade.targetting,
    tags: [Tag.arrow, Tag.vulnerable],
  ),
  Upgrade.demolish_unrestricted: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 250,
    costToken: 'basic',
    iconPath: 'assets/sprites/demolish_unrestricted_icon.png',
    value: (int l) => l,
    dependency: Upgrade.gem_drops,
  ),
  Upgrade.demolish_refund_amount: UpgradeData(
    maxLevel: 5,
    cost: (int _l) => [100, 200, 300, 400, 500][_l],
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    costToken: 'basic',
    iconPath: 'assets/sprites/demolish_refund_amount_icon.png',
    dependency: Upgrade.demolish_unrestricted,
  ),
  Upgrade.demolish_refund_amount_2: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    costToken: 'challenge',
    iconPath: 'assets/sprites/demolish_refund_amount_icon.png',
    dependency: Upgrade.demolish_refund_amount,
  ),
  Upgrade.demolish_explosion: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 200, 250][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/demolish_explosion_icon.png',
    value: (int l) => l * 2.0,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.demolish_refund_amount,
  ),
  Upgrade.gem_shot: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 75, 125, 200, 350][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/gem_shot_icon.png',
    dependency: Upgrade.gem_drops,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.slow_tower_damage_link: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/damage_link_icon.png',
    value: (int l) => l * 0.3,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_fire_rate,
    data: {
      'damage': {
        'value': 0.15,
        'format': ValueFormat.percentage,
      },
      'reduced_effectiveness_after': 10,
      'damage_reduction_multiplier': 0.65,
    },
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_damage_link_increase: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [75, 150, 350, 650, 1250][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/damage_link_increase_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_damage_link,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_damage_link_share_sources: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/damage_link_share_sources_icon.png',
    dependency: Upgrade.slow_tower_damage_link,
    tags: [Tag.slow],
  ),
  Upgrade.slow_vulnerable: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 200, 400, 800][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_damage_multiplier.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_fire_rate,
    data: {
      'vulnerable_damage': ((VulnerableStatus.BASE_DAMAGE_MULTIPLIER - 1.0) * 100).round(),
    },
    keywords: [Keyword.vulnerable],
    tags: [Tag.slow, Tag.vulnerable],
  ),
  Upgrade.slow_amount: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 200, 400, 800][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_icon.png',
    value: (int l) => l * 0.02,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_unlock,
    tags: [Tag.slow],
  ),
  Upgrade.slow_duration: UpgradeData(
    maxLevel: 4,
    cost: (int l) => [100, 200, 300, 400][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_duration_icon.png',
    value: (int l) => l * 0.05,
    dependency: Upgrade.slow_amount,
    tags: [Tag.slow],
  ),
  Upgrade.slow_duration_2: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/slow_duration_icon.png',
    value: (int l) => l * 0.15,
    dependency: Upgrade.slow_duration,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_fire_rate: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [25, 75, 200][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_tower_fire_rate_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_unlock,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_charge_buff: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/slow_tower_charge_buff_icon.png',
    value: (int l) => l * 0.25,
    dependency: Upgrade.slow_tower_fire_rate,
    keywords: [Keyword.charge],
    tags: [Tag.charge],
  ),
  Upgrade.charge_amount: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [200, 400, 800][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_tower_charge_buff_icon.png',
    value: (int l) => l * 0.05,
    dependency: Upgrade.slow_tower_charge_buff,
    tags: [Tag.charge],
  ),
  Upgrade.charge_amount_2: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/slow_tower_charge_buff_icon.png',
    value: (int l) => l * 0.1,
    dependency: Upgrade.charge_amount,
    tags: [Tag.charge],
  ),
  Upgrade.charge_damage_bonus: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 150, 250, 400][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/charge_damage_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_charge_buff,
    tags: [Tag.charge],
  ),
  Upgrade.slow_damage_bonus: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [150, 250, 400, 650, 1000][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/slow_damage_bonus_icon.png',
    value: (int l) => l * 0.02,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_vulnerable,
    tags: [Tag.slow],
  ),
  Upgrade.charge_damage_stacking: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/charge_damage_stacking_icon.png',
    value: (int l) => l * 15,
    dependency: Upgrade.charge_damage_bonus,
    tags: [Tag.charge],
  ),
  Upgrade.slow_zone: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 100, 150][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/slow_zone_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_duration,
    data: {
      'duration': 5.0,
    },
    tags: [Tag.slow, Tag.pool],
    keywords: [Keyword.pool],
  ),
  Upgrade.gem_cannon_damage: UpgradeData(
    maxLevel: 10,
    cost: (int l) => [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/gem_cannon_damage_icon.png',
    value: (int l) => l * 5,
    dependency: Upgrade.gem_cannon,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_damage_extra: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 200, 400, 800][l],
    costToken: 'advanced',
    value: (int l) => l * 5,
    dependency: Upgrade.gem_cannon_crit_chance,
    iconPath: 'assets/sprites/gem_cannon_damage_icon.png',
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_fire_rate: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [1, 2][l],
    costToken: 'time',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/gem_cannon_fire_rate.png',
    dependency: Upgrade.gem_cannon,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.explosive_grunts_chance: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [25, 150, 500][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/explosion_chance_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_grunts,
    tags: [Tag.explosive],
  ),

  Upgrade.explosive_runners_chance: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/explosive_runners_icon.png',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_grunts_chance,
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_damage: UpgradeData(
    maxLevel: 7,
    cost: (int l) => [30, 90, 220, 450, 1000, 1500, 2000][l],
    costToken: 'basic',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/explosion_damage_icon.png',
    dependency: Upgrade.explosive_grunts,
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_damage_2: UpgradeData(
    maxLevel: 5,
    cost: (int _l) => [50, 100, 150, 250, 400][_l],
    costToken: 'advanced',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosion_range_increase,
    iconPath: 'assets/sprites/explosion_damage_icon.png',
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_bosses: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 250, 750][l],
    costToken: 'basic',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_bosses_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_elites,
    data: {
      'damage': {
        'value': 1.0,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_elites: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 250, 750][l],
    costToken: 'basic',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_elites_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_damage,
    data: {
      'damage': {
        'value': 0.5,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_bosses_2: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 100, 150][l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_bosses_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_bosses,
  ),
  Upgrade.explosive_elites_2: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 100, 150][l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_elites_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_elites,
  ),
  Upgrade.explosion_fireball: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_icon.png',
    dependency: Upgrade.explosive_damage,
    tags: [Tag.explosive, Tag.burn],
    data: {
      'burn_damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
      'explosion_damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.explosion_fireball_chance: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [150, 300, 500, 1000, 1500][l],
    costToken: 'basic',
    value: (int l) => l * 0.03,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_icon.png',
    dependency: Upgrade.explosion_fireball,
    tags: [Tag.explosive, Tag.burn],
  ),
  Upgrade.explosion_fireball_burn_damage: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 125, 250, 375, 500][l],
    costToken: 'advanced',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_damage_icon.png',
    dependency: Upgrade.explosion_fireball_chance,
  ),
  Upgrade.explosion_fireball_explosion_damage: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 125, 250, 375, 500][l],
    costToken: 'advanced',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_damage_icon.png',
    dependency: Upgrade.explosion_fireball_chance,
  ),
  Upgrade.explosion_fireball_double_chance: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/double_fireball_icon.png',
    dependency: Upgrade.explosion_fireball_chance,
  ),
  Upgrade.explosion_range_increase: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 200, 400, 800, 1500][l],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    iconPath: 'assets/sprites/explosion_range_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_damage,
    tags: [Tag.explosive],
  ),
  Upgrade.explosion_tower_charge: UpgradeData(
    maxLevel: 4,
    cost: (int _l) => [75, 150, 300, 750][_l],
    costToken: 'advanced',
    value: (int l) => l * 0.15,
    iconPath: 'assets/sprites/explosion_charge_icon.png',
    dependency: Upgrade.explosive_damage_2,
    tags: [Tag.explosive],
    keywords: [Keyword.charge],
  ),

  Upgrade.explosion_tower_charge_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'time',
    value: (int l) => l * 0.15,
    iconPath: 'assets/sprites/explosion_charge_icon.png',
    dependency: Upgrade.explosion_tower_charge,
    tags: [Tag.explosive],
  ),
  Upgrade.explosion_chance_to_create_pool: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [50, 150, 300][_l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/explosive_pool_icon.png',
    dependency: Upgrade.explosion_tower_charge,
    tags: [Tag.explosive],
    keywords: [Keyword.pool],
  ),
  Upgrade.gem_cannon_shot_reimbursement_chance: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/gem_cannon_reimburse.png',
    dependency: Upgrade.gem_cannon_damage,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_crit_chance: UpgradeData(
    maxLevel: 3,
    iconPath: 'assets/sprites/gem_cannon_crit_icon.png',
    cost: (int l) => [100, 200, 400][l],
    costToken: 'basic',
    dependency: Upgrade.gem_cannon_damage,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    keywords: [Keyword.critical_hit],
    tags: [Tag.coin_cannon, Tag.crit],
  ),
  Upgrade.auto_collect_gems: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 5000,
    value: (int l) => l,
    isMilestone: true,
    defaultUnlockedOnMobile: true,
    costToken: 'basic',
    iconPath: 'assets/sprites/auto_collect_gems_icon.png',
    dependency: Upgrade.tower_upgrade_unlock,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/unlock_bank_tower.png',
    dependency: Upgrade.basic_token_drops,
    data: {
      'chance_to_spawn_coin': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_chance_to_spawn_coin: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [25, 50, 100, 200, 400][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/bank_tower_coin_icon.png',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.bank_tower_unlock,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_pool: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 250,
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_pool_icon.png',
    dependency: Upgrade.bank_tower_chance_to_spawn_coin,
    keywords: [Keyword.pool],
    tags: [Tag.economy, Tag.pool],
  ),
  Upgrade.bank_tower_tokens: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 100,
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_token_icon.png',
    dependency: Upgrade.bank_tower_chance_to_spawn_coin,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_basic_tokens_multiplier: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l * 1.0,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/bank_tower_token_multiplier_icon.png',
    dependency: Upgrade.bank_tower_tokens,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_damage: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l * 0.015,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/bank_tower_damage_icon.png',
    dependency: Upgrade.bank_tower_tokens,
    tags: [Tag.economy],
    data: {
      'min_damage': 25,
    },
  ),
  Upgrade.bank_tower_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => [50, 250][_l],
    costToken: 'advanced',
    value: (int l) => l * 0.005,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/bank_tower_damage_icon.png',
    dependency: Upgrade.bank_tower_damage,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_accelerated_enemies: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 2,
    costToken: 'time',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_accelerated_coin_icon.png',
    dependency: Upgrade.bank_tower_tokens,
    tags: [Tag.economy],
  ),
  Upgrade.gem_cannon_damage_expensive: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [500, 1500][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/gem_cannon_expensive_damage_icon.png',
    dependency: Upgrade.gem_cannon_damage,
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    data: {
      'cost_increase': {
        'value': (int l) => l,
        'format': ValueFormat.number,
      },
    },
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_damage_expensive_extra: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [250, 500][l],
    costToken: 'advanced',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.gem_cannon_damage_expensive,
    iconPath: 'assets/sprites/gem_cannon_expensive_damage_icon.png',
    tags: [Tag.coin_cannon],
    data: {
      'cost_increase': {
        'value': (int l) => l,
        'format': ValueFormat.number,
      },
    },
  ),
  Upgrade.economy_damage_increase_by_coins: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 200, 400][l],
    costToken: 'advanced',
    value: (int l) => l * 0.0005,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/coins_damage_icon.png',
    dependency: Upgrade.gem_shot,
    tags: [Tag.economy],
    data: {
      'max_damage_increase': {
        'value': 0.3,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.economy_gem_interest: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 300, 500][l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.starting_gems_2,
    iconPath: 'assets/sprites/interest_icon.png',
    tags: [Tag.economy],
  ),
  Upgrade.economy_enemy_defeat_upgrade_discount: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [250, 500, 750][l],
    costToken: 'advanced',
    value: (int l) => l * 0.0025,
    valueFormat: ValueFormat.percentage_decimals,
    dependency: Upgrade.economy_damage_increase_by_coins,
    iconPath: 'assets/sprites/defeat_upgrade_discount_icon.png',
    tags: [Tag.economy],
  ),
  Upgrade.economy_uncapped_levels: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l,
    dependency: Upgrade.economy_enemy_defeat_upgrade_discount,
    iconPath: 'assets/sprites/uncapped_levels_icon.png',
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_number_coins: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [1, 2][l],
    costToken: 'challenge',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_coin_icon.png',
    dependency: Upgrade.bank_tower_chance_to_spawn_coin,
    tags: [Tag.economy],
  ),
  Upgrade.burn_damage: UpgradeData(
    maxLevel: 6,
    cost: (int l) => [50, 100, 200, 300, 500, 750][l],
    costToken: 'basic',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.burn_ticks,
    tags: [Tag.burn],
  ),
  Upgrade.burn_damage_fire_tower: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [25, 50, 100, 200, 500][l],
    costToken: 'basic',
    value: (int l) => l * 2,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.fire_tower_unlock,
  ),
  Upgrade.burn_concentration: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [100, 150, 200, 250, 300][l],
    costToken: 'basic',
    value: (int l) => l * 0.3,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_concentration_icon.png',
    dependency: Upgrade.burn_damage,
    data: {'max_targets': 1},
    tags: [Tag.burn],
  ),
  Upgrade.burn_damage_extra: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 150, 300, 500, 750][l],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.burn_concentration,
    tags: [Tag.burn],
  ),
  Upgrade.burn_damage_extra_for_reduced_tick_rate: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 200, 400][l],
    costToken: 'advanced',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.burn_damage_extra,
    tags: [Tag.burn],
    data: {
      'damage_increase': {'value': (int l) => l * 0.2, 'format': ValueFormat.percentage},
    },
  ),
  Upgrade.burn_ticks: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [50, 100, 250, 400, 1000][l],
    costToken: 'basic',
    value: (int l) => l * 1,
    iconPath: 'assets/sprites/burn_ticks_icon.png',
    dependency: Upgrade.burn_damage_fire_tower,
    tags: [Tag.burn],
  ),
  Upgrade.burn_ticks_extra: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => 2 * l,
    iconPath: 'assets/sprites/burn_ticks_icon.png',
    dependency: Upgrade.burn_ticks,
    tags: [Tag.burn],
  ),

  Upgrade.burn_crit: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l,
    iconPath: 'assets/sprites/burn_crit_icon.png',
    dependency: Upgrade.burn_damage,
    keywords: [Keyword.critical_hit],
    data: {
      'damage': {
        'value': 0.15,
        'format': ValueFormat.percentage,
      },
      'burn_crit_chance': {
        'value': (int l) => l * 0.05,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_crit_chance: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 200, 400][l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_crit_icon.png',
    dependency: Upgrade.burn_crit,
    tags: [Tag.burn, Tag.crit],
  ),
  Upgrade.burn_stacking_damage: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 200, 400][l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_stacking_damage_icon.png',
    dependency: Upgrade.burn_damage,
  ),
  Upgrade.burn_spreading: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    value: (int l) => l * 0.075,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/burn_spreading_icon.png',
    dependency: Upgrade.burn_ticks,
    tags: [Tag.burn],
  ),
  Upgrade.burn_spread_chance: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [50, 250][l],
    costToken: 'advanced',
    value: (int l) => l * 0.025,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/burn_spreading_icon.png',
    dependency: Upgrade.burn_spreading,
    tags: [Tag.burn],
  ),
  Upgrade.burn_spread_to_burning: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_spreading_icon.png',
    dependency: Upgrade.burn_spread_chance,
    tags: [Tag.burn],
  ),
  Upgrade.burn_pool_apply_burn: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [50, 150][l],
    costToken: 'advanced',
    value: (int l) => l * 10,
    iconPath: 'assets/sprites/burn_pool_icon.png',
    dependency: Upgrade.burn_spreading,
    tags: [Tag.burn],
  ),
  Upgrade.burn_pool_apply_burn_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => 10 * l,
    iconPath: 'assets/sprites/burn_pool_icon.png',
    dependency: Upgrade.burn_pool_apply_burn,
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_rate_accelerated_enemies: UpgradeData(
    maxLevel: 4,
    cost: (int _l) => [50, 200, 400, 800][_l],
    costToken: 'advanced',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_rate_icon.png',
    dependency: Upgrade.burn_damage_extra,
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_rate_accelerated_enemies_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'time',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_rate_icon.png',
    dependency: Upgrade.burn_tick_rate_accelerated_enemies,
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_rate: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => 1,
    costToken: 'time',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_rate_icon.png',
    dependency: Upgrade.burn_damage,
    tags: [Tag.burn],
  ),
  Upgrade.burn_crit_add_tick: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 150,
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/burn_crit_tick_icon.png',
    dependency: Upgrade.burn_crit,
    tags: [Tag.burn, Tag.crit],
  ),

  Upgrade.fire_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/fire_tower_icon.png',
    dependency: Upgrade.core_health,
    data: {
      'tick_count': BurningStatus.DEFAULT_TICKS,
      'stack_damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
      'reduced_effectiveness_after': 1000,
      'reduced_effectiveness_exponent': 0.75,
      'second_reduced_effectiveness_after': 2500,
      'second_reduced_effectiveness_exponent': 0.55,
    },
    tags: [Tag.burn],
  ),
  Upgrade.lightning_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    dependency: Upgrade.arrow_tower_fire_rate,
    iconPath: 'assets/sprites/lightning_tower_icon.png',
    value: (int _l) => 1,
    data: {
      'jump_damage_reduction': {
        'value': 0.3,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.lightning],
  ),

  Upgrade.lightning_tower_spread_status: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'star',
    iconPath: 'assets/sprites/lightning_status_link_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_jumps: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [25, 250, 500][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_jumps_icon.png',
    dependency: Upgrade.lightning_tower_unlock,
    value: (int l) => l,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_extra_jumps: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [50, 150, 300][_l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_jumps_icon.png',
    dependency: Upgrade.lightning_tower_jumps,
    value: (int l) => l,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_damage: UpgradeData(
    maxLevel: 8,
    cost: (int l) => [50, 150, 150, 200, 250, 500, 750, 1000][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_damage_icon.png',
    dependency: Upgrade.lightning_tower_jumps,
    value: (int l) => l * 5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_damage_extra: UpgradeData(
    maxLevel: 8,
    cost: (int l) => [50, 75, 100, 200, 500, 750, 1000, 1500][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_damage_icon.png',
    dependency: Upgrade.lightning_tower_damage,
    value: (int l) => l * 5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_speed: UpgradeData(
    maxLevel: 5,
    cost: (int l) => [25, 50, 100, 500, 1000][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_rate_icon.png',
    dependency: Upgrade.lightning_tower_unlock,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_crit_chance: UpgradeData(
    maxLevel: 6,
    cost: (int l) => [100, 200, 400, 800, 1200, 1600][l],
    costToken: 'basic',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/lightning_crit_chance_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    tags: [Tag.lightning, Tag.crit],
  ),
  Upgrade.lightning_tower_crit_charge: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 200, 500][l],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/lightning_crit_charge_icon.png',
    dependency: Upgrade.lightning_tower_crit_chance,
    keywords: [Keyword.charge],
    tags: [Tag.charge, Tag.lightning],
  ),
  Upgrade.lightning_tower_charge_extra_jumps: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/lightning_jumps_icon.png',
    dependency: Upgrade.lightning_tower_crit_charge,
    value: (int l) => l,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_extra_speed: UpgradeData(
    maxLevel: 3,
    cost: (int _l) => [1, 2, 3][_l],
    costToken: 'time',
    iconPath: 'assets/sprites/lightning_rate_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_overkill_damage: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 250, 500][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/overkill_icon.png',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.lightning_tower_unlock,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_overkill_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/overkill_icon.png',
    dependency: Upgrade.lightning_tower_overkill_damage,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_overkill_retrigger_chance: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => [250, 500][_l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/overkill_retrigger_icon.png',
    dependency: Upgrade.lightning_tower_overkill_damage_extra,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_jump_damage_reduction: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 250, 1000][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_jump_damage_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_chance_to_jump_again: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [250, 500, 750][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_accelerated_jumps_icon.png',
    dependency: Upgrade.lightning_tower_jump_damage_reduction,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_chance_to_jump_again_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/lightning_accelerated_jumps_icon.png',
    dependency: Upgrade.lightning_tower_chance_to_jump_again,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_apply_shock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 200,
    costToken: 'basic',
    iconPath: 'assets/sprites/shock_icon.png',
    dependency: Upgrade.lightning_tower_damage,
    value: (int _l) => 0.75,
    data: {
      'shock_count': 5,
    },
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_stun_increase_damage: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 250, 500][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/shock_icon.png',
    dependency: Upgrade.lightning_tower_apply_shock,
    value: (int l) => 0.1 * l,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_stun_increase_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/shock_icon.png',
    dependency: Upgrade.lightning_tower_stun_increase_damage,
    value: (int l) => 0.25 * l,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_shock_stun_duration: UpgradeData(
    maxLevel: 2,
    cost: (int l) => [100, 250][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/discharge_duration_icon.png',
    dependency: Upgrade.lightning_tower_apply_shock,
    value: (int l) => l * 0.5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_shock_stun_duration_extra: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'time',
    iconPath: 'assets/sprites/discharge_duration_icon.png',
    dependency: Upgrade.lightning_tower_shock_stun_duration,
    value: (int l) => l * 0.5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_discharge_combust: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/discharge_combust_icon.png',
    dependency: Upgrade.lightning_tower_apply_shock,
    keywords: [Keyword.combustion],
    data: {
      'combust_ticks': 50,
    },
    tags: [Tag.lightning, Tag.explosive],
  ),
  Upgrade.lightning_tower_jump_range: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 100, 200][l],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_jump_range_icon.png',
    dependency: Upgrade.lightning_tower_jump_damage_reduction,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.increased_vulnerable_damage_undamaged_enemies: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/vulnerability_effect_icon.png',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.vulnerable_damage_multiplier,
    tags: [Tag.core, Tag.vulnerable],
  ),
  Upgrade.boss_defeat_partial_token: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 50,
    costToken: 'basic',
    iconPath: 'assets/sprites/boss_defeat_partial_token.png',
    dependency: Upgrade.basic_token_drops,
    data: {
      'drop_coin_per_health': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.economy],
  ),
  Upgrade.boss_damage_taken_basic_token_increase: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [100, 200, 300][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/boss_defeat_partial_token_increase.png',
    dependency: Upgrade.boss_defeat_partial_token,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_add_vulnerable: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => [500, 750][_l],
    costToken: 'basic',
    iconPath: 'assets/sprites/bank_tower_vulnerable_icon.png',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.bank_tower_unlock,
    keywords: [Keyword.vulnerable],
    data: {
      'vulnerable_duration': 1.0,
      'vulnerable_damage': ((VulnerableStatus.BASE_DAMAGE_MULTIPLIER - 1.0) * 100).round(),
    },
    tags: [Tag.economy, Tag.vulnerable],
  ),
  Upgrade.bank_tower_vulnerable_duration: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [250, 500, 750][l],
    costToken: 'basic',
    iconPath: 'assets/sprites/bank_tower_vulnerable_duration_icon.png',
    value: (int l) => l * 1.0,
    dependency: Upgrade.bank_tower_add_vulnerable,
    tags: [Tag.economy],
  ),
  Upgrade.status_effect_count_increase_damage: UpgradeData(
    maxLevel: 3,
    cost: (int l) => [50, 200, 400][l],
    costToken: 'advanced',
    value: (int l) => l * 0.01,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/status_count_damage_icon.png',
    dependency: Upgrade.lightning_tower_spread_status,
    tags: [],
  ),
  Upgrade.status_effect_count_increase_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: (int _l) => 1,
    costToken: 'challenge',
    value: (int l) => l * 0.01,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/status_count_damage_icon.png',
    dependency: Upgrade.status_effect_count_increase_damage,
    tags: [],
  ),
  Upgrade.artifacts_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 4,
    costToken: 'star',
    iconPath: 'assets/sprites/artifact_unlock_icon.png',
    value: (int l) => l,
    dependency: Upgrade.level_challenge_unlock,
    isMilestone: true,
    keywords: [Keyword.artifact_unlock],
    tags: [Tag.core],
    availableInDemo: false,
  ),
  Upgrade.fire_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/fire_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.FIRE,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [Tag.burn],
  ),
  Upgrade.fire_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 10,
    costToken: 'star',
    iconPath: 'assets/sprites/fire_artifact_icon.png',
    dependency: Upgrade.fire_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_FIRE,
    data: {
      'enchant': Enchants.Type.FIRE,
    },
    tags: [Tag.burn],
  ),
  Upgrade.light_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/light_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.LIGHT,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [Tag.lightning],
  ),
  Upgrade.light_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 10,
    costToken: 'star',
    iconPath: 'assets/sprites/light_artifact_icon.png',
    dependency: Upgrade.light_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_LIGHT,
    data: {
      'enchant': Enchants.Type.LIGHT,
    },
    tags: [Tag.lightning],
  ),
  Upgrade.ice_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/ice_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.ICE,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [],
  ),
  Upgrade.ice_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 10,
    costToken: 'star',
    iconPath: 'assets/sprites/ice_artifact_icon.png',
    dependency: Upgrade.ice_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_ICE,
    data: {
      'enchant': Enchants.Type.ICE,
    },
    tags: [],
  ),
  Upgrade.earth_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/earth_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.EARTH,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [],
  ),
  Upgrade.earth_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 10,
    costToken: 'star',
    iconPath: 'assets/sprites/earth_artifact_icon.png',
    dependency: Upgrade.earth_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_EARTH,
    data: {
      'enchant': Enchants.Type.EARTH,
    },
    tags: [],
  ),
  Upgrade.wind_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/wind_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.WIND,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [],
  ),
  Upgrade.wind_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 10,
    costToken: 'star',
    iconPath: 'assets/sprites/wind_artifact_icon.png',
    dependency: Upgrade.wind_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_WIND,
    data: {
      'enchant': Enchants.Type.WIND,
    },
    tags: [],
  ),
  Upgrade.build_presets_unlock: UpgradeData(
    maxLevel: 1,
    cost: (int _l) => 2500,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/build_presets_icon.png',
    dependency: Upgrade.level_challenge_unlock,
    tags: [Tag.misc],
  ),
};
