import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> arrowUpgrades = {
  Upgrade.arrow_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'basic',
    iconPath: 'assets/sprites/arrow_tower_icon.png',
    activationLevel: ActivationLevel.available,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_damage: UpgradeData(
    maxLevel: 10,
    cost: [3, 5, 15, 50, 150, 500, 800, 1250, 1750, 2500],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_unlock,
    value: (int l) => l * 5,
    iconPath: 'assets/sprites/arrow_damage_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_build_cost_damage_multiplier: UpgradeData(
    maxLevel: 1,
    cost: 250,
    costToken: 'advanced',
    dependency: Upgrade.vulnerable_damage_multiplier,
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    data: {
      'build_cost_multiplier': {
        'value': (int l) => 0.5 * l,
        'format': ValueFormat.percentage,
      },
    },
    iconPath: 'assets/sprites/arrow_tower_build_cost_damage.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_upgrade_cost_damage_multiplier: UpgradeData(
    maxLevel: 1,
    cost: 250,
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_build_cost_damage_multiplier,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    data: {
      'upgrade_cost_multiplier': {
        'value': (int l) => 0.5 * l,
        'format': ValueFormat.percentage,
      },
    },
    iconPath: 'assets/sprites/arrow_tower_build_cost_damage.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_fire_rate: UpgradeData(
    maxLevel: 2,
    cost: [3, 50],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_unlock,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/tower_fire_rate_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_fire_rate_2: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    dependency: Upgrade.arrow_tower_fire_rate,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/tower_fire_rate_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_fire_rate_3: UpgradeData(
    maxLevel: 2,
    cost: [1, 2],
    costToken: 'time',
    dependency: Upgrade.arrow_tower_range,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/tower_fire_rate_icon.png',
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_crit_chance: UpgradeData(
    maxLevel: 3,
    iconPath: 'assets/sprites/crit_chance_icon.png',
    cost: [25, 100, 400],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_damage,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    keywords: [Keyword.critical_hit],
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_crit_damage: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/crit_damage_icon.png',
    cost: [50, 100, 150, 250, 400],
    costToken: 'basic',
    dependency: Upgrade.arrow_tower_crit_chance,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_multicrit: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_icon.png',
    cost: 1,
    costToken: 'star',
    dependency: Upgrade.arrow_tower_crit_chance,
    value: (int l) => l,
    data: {
      'damage': {
        'value': 1.0,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_multicrit_combustion: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_combust_icon.png',
    cost: 250,
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_multicrit,
    value: (int l) => l,
    data: {
      'combust_ticks': 3,
    },
    keywords: [Keyword.combustion],
    tags: [Tag.arrow, Tag.crit, Tag.combust],
  ),
  Upgrade.arrow_tower_multicrit_2: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_icon.png',
    cost: 50,
    costToken: 'advanced',
    data: {
      'level_required': 3,
    },
    dependency: Upgrade.arrow_tower_multicrit,
    value: (int l) => l,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_heavy: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_heavy_icon.png',
    cost: 1,
    costToken: 'star',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_multicrit_2,
    data: {
      'reduced_fire_rate': {
        'value': 0.8,
        'format': ValueFormat.percentage,
      },
      'increased_damage': {
        'value': 7.0,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_range: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/arrow_tower_range_icon.png',
    cost: [50, 100, 250, 500, 750],
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_heavy,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_crit_chance_2: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/crit_chance_icon.png',
    cost: [50, 100, 250, 500, 750],
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_heavy,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_crit_damage_2: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/crit_damage_icon.png',
    cost: [50, 100, 250, 500, 750],
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_crit_chance_2,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_multicrit_leveled: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/multicrit_icon.png',
    cost: 1,
    value: (int l) => l,
    costToken: 'challenge',
    data: {
      'level_required': 5,
    },
    dependency: Upgrade.arrow_tower_crit_chance_2,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_damage_at_range: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_range_damage_icon.png',
    cost: 500,
    costToken: 'advanced',
    dependency: Upgrade.arrow_tower_range,
    value: (int l) => l * 0.025,
    valueFormat: ValueFormat.percentage_decimals,
    data: {
      'per_range_unit': 100,
    },
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_unharmed_crit_chance: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_target_highest_health_icon.png',
    cost: 1,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    costToken: 'challenge',
    dependency: Upgrade.arrow_tower_damage_3,
    tags: [Tag.arrow, Tag.crit],
  ),
  Upgrade.arrow_tower_damage_2: UpgradeData(
    maxLevel: 5,
    iconPath: 'assets/sprites/arrow_damage_icon.png',
    cost: [50, 250, 500, 750, 1000],
    costToken: 'advanced',
    value: (int l) => l * 5,
    dependency: Upgrade.vulnerable_damage_multiplier,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_damage_3: UpgradeData(
    maxLevel: 3,
    iconPath: 'assets/sprites/arrow_damage_icon.png',
    cost: [100, 200, 400],
    costToken: 'advanced',
    value: (int l) => l * 5,
    dependency: Upgrade.arrow_tower_heavy,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_pierce_shield: UpgradeData(
    maxLevel: 2,
    iconPath: 'assets/sprites/arrow_tower_shielded_icon.png',
    cost: [100, 250],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.arrow_tower_heavy,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_disable: UpgradeData(
    maxLevel: 1,
    iconPath: 'assets/sprites/arrow_tower_disable_icon.png',
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_pierce_shield,
    tags: [Tag.arrow],
    data: {
      'key_action_string': 'SHIFT',
    },
  ),
  Upgrade.arrow_tower_multishot: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/multishot_icon.png',
    dependency: Upgrade.arrow_tower_fire_rate,
    value: (int l) => l,
    data: {
      'damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_multishot_triple_when_leveled: UpgradeData(
    maxLevel: 1,
    cost: 2,
    costToken: 'challenge',
    iconPath: 'assets/sprites/tripleshot_icon.png',
    dependency: Upgrade.arrow_tower_poison_vulnerable,
    value: (int l) => l,
    tags: [Tag.arrow, Tag.poison],
    data: {
      'level_required': {
        'value': 5,
        'format': ValueFormat.number,
      },
      'damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.arrow_tower_multishot_increased_damage: UpgradeData(
    maxLevel: 3,
    cost: [100, 300, 500],
    costToken: 'basic',
    iconPath: 'assets/sprites/multishot_damage_icon.png',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.arrow_tower_multishot,
    tags: [Tag.arrow],
  ),
  Upgrade.arrow_tower_poison: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/poison_icon.png',
    value: 2,
    data: {'reduced_effectiveness_after': 100},
    dependency: Upgrade.arrow_tower_fire_rate_increase_damage_decrease,
    keywords: [Keyword.poison],
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_more_poison: UpgradeData(
    maxLevel: 3,
    cost: [100, 250, 500],
    costToken: 'advanced',
    iconPath: 'assets/sprites/poison_stacks_icon.png',
    value: (int l) => 1 * l,
    dependency: Upgrade.arrow_tower_poison,
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_poison_on_shields: UpgradeData(
    maxLevel: 1,
    cost: 300,
    costToken: 'advanced',
    iconPath: 'assets/sprites/shielded_poison_icon.png',
    dependency: Upgrade.arrow_tower_more_poison,
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_poison_pool: UpgradeData(
    maxLevel: 3,
    cost: [100, 200, 400],
    costToken: 'advanced',
    iconPath: 'assets/sprites/poison_pool_icon.png',
    value: (int l) => 5 * l,
    dependency: Upgrade.arrow_tower_more_poison,
    tags: [Tag.poison, Tag.pool],
  ),
  Upgrade.arrow_tower_crit_poison: UpgradeData(
    maxLevel: 3,
    cost: [50, 100, 200],
    costToken: 'advanced',
    iconPath: 'assets/sprites/crit_poison_icon.png',
    value: (int l) => 0.03 * l,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.arrow_tower_more_poison,
    tags: [Tag.poison],
  ),
  Upgrade.arrow_tower_poison_vulnerable: UpgradeData(
    maxLevel: 2,
    cost: [150, 300],
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/vulnerable_poison_icon.png',
    dependency: Upgrade.arrow_tower_crit_poison,
    tags: [Tag.poison, Tag.vulnerable],
  ),
  Upgrade.arrow_tower_poison_charge_add_stacks: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/charge_poison_icon.png',
    dependency: Upgrade.arrow_tower_crit_poison,
    value: (int l) => l,
    tags: [Tag.poison, Tag.charge],
    data: {
      'add_stacks': {'value': 10, 'format': ValueFormat.number},
    },
  ),
  Upgrade.arrow_tower_fire_rate_increase_damage_decrease: UpgradeData(
    maxLevel: 3,
    cost: [100, 250, 500],
    costToken: 'advanced',
    iconPath: 'assets/sprites/light_arrows_icon.png',
    dependency: Upgrade.arrow_tower_multishot,
    tags: [Tag.arrow],
    value: (int l) => 0.1 * l,
    valueFormat: ValueFormat.percentage,
    data: {
      'decrease_damage': {
        'value': (int l) => 0.05 * l,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.arrow_tower_leveling_fire_rate_2: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/light_arrows_icon.png',
    dependency: Upgrade.arrow_tower_crit_poison,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.arrow],
    data: {
      'decrease_damage': {
        'value': (int l) => 0.1 * l,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.targetting: UpgradeData(
    maxLevel: 1,
    cost: 20,
    costToken: 'basic',
    iconPath: 'assets/sprites/targetting_icon.png',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_damage,
    data: {
      'vulnerable_damage':
          ((VulnerableStatus.BASE_DAMAGE_MULTIPLIER - 1.0) * 100).round(),
    },
    keywords: [Keyword.vulnerable],
    tags: [Tag.arrow, Tag.vulnerable],
  ),
  Upgrade.vulnerable_damage_multiplier: UpgradeData(
    maxLevel: 6,
    cost: [25, 50, 100, 200, 400, 800],
    costToken: 'basic',
    iconPath: 'assets/sprites/vulnerability_effect_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.targetting,
    tags: [Tag.arrow, Tag.vulnerable],
  ),
  Upgrade.targetting_auto: UpgradeData(
    maxLevel: 1,
    cost: 50,
    costToken: 'basic',
    iconPath: 'assets/sprites/targetting_damage_icon.png',
    value: (int l) => l,
    dependency: Upgrade.targetting,
    tags: [Tag.arrow, Tag.vulnerable],
  ),
  Upgrade.increased_vulnerable_damage_undamaged_enemies: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/vulnerability_effect_icon.png',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.vulnerable_damage_multiplier,
    tags: [Tag.core, Tag.vulnerable],
  ),
};
