import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> artifactUpgrades = {
  Upgrade.artifacts_unlock: UpgradeData(
    maxLevel: 1,
    cost: 4,
    costToken: 'star',
    iconPath: 'assets/sprites/artifact_unlock_icon.png',
    value: (int l) => l,
    dependency: Upgrade.level_challenge_unlock,
    isMilestone: true,
    keywords: [Keyword.artifact_unlock],
    tags: [Tag.core],
    availableInDemo: false,
  ),
  Upgrade.fire_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/fire_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.FIRE,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [Tag.burn],
  ),
  Upgrade.fire_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: 10,
    costToken: 'star',
    iconPath: 'assets/sprites/fire_artifact_icon.png',
    dependency: Upgrade.fire_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_FIRE,
    data: {
      'enchant': Enchants.Type.FIRE,
    },
    tags: [Tag.burn],
  ),
  Upgrade.light_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/light_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.LIGHT,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [Tag.lightning],
  ),
  Upgrade.light_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: 10,
    costToken: 'star',
    iconPath: 'assets/sprites/light_artifact_icon.png',
    dependency: Upgrade.light_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_LIGHT,
    data: {
      'enchant': Enchants.Type.LIGHT,
    },
    tags: [Tag.lightning],
  ),
  Upgrade.ice_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/ice_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.ICE,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [],
  ),
  Upgrade.ice_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: 10,
    costToken: 'star',
    iconPath: 'assets/sprites/ice_artifact_icon.png',
    dependency: Upgrade.ice_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_ICE,
    data: {
      'enchant': Enchants.Type.ICE,
    },
    tags: [],
  ),
  Upgrade.earth_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/earth_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.EARTH,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [],
  ),
  Upgrade.earth_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: 10,
    costToken: 'star',
    iconPath: 'assets/sprites/earth_artifact_icon.png',
    dependency: Upgrade.earth_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_EARTH,
    data: {
      'enchant': Enchants.Type.EARTH,
    },
    tags: [],
  ),
  Upgrade.wind_artifact_unlock: UpgradeData(
    maxLevel: 1,
    cost: artifact_cost,
    costToken: 'advanced',
    iconPath: 'assets/sprites/wind_artifact_icon.png',
    dependency: Upgrade.artifacts_unlock,
    dynamicCost: true,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    data: {
      'enchant': Enchants.Type.WIND,
    },
    keywords: [Keyword.artifact_unlock],
    tags: [],
  ),
  Upgrade.wind_artifact_2_unlock: UpgradeData(
    maxLevel: 1,
    cost: 10,
    costToken: 'star',
    iconPath: 'assets/sprites/wind_artifact_icon.png',
    dependency: Upgrade.wind_artifact_unlock,
    value: (int l) => l,
    isMilestone: true,
    isArtifact: true,
    requiredCompletedLevel: Levels.LevelType.LEVEL_ARTIFACT_WIND,
    data: {
      'enchant': Enchants.Type.WIND,
    },
    tags: [],
  ),
};
