import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> burnUpgrades = {
  Upgrade.burn_damage: UpgradeData(
    maxLevel: 6,
    cost: [50, 100, 200, 300, 500, 750],
    costToken: 'basic',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.burn_ticks,
    tags: [Tag.burn],
  ),
  Upgrade.burn_damage_fire_tower: UpgradeData(
    maxLevel: 5,
    cost: [25, 50, 100, 200, 500],
    costToken: 'basic',
    value: (int l) => l * 2,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.fire_tower_unlock,
  ),
  Upgrade.burn_concentration: UpgradeData(
    maxLevel: 5,
    cost: [100, 150, 200, 250, 300],
    costToken: 'basic',
    value: (int l) => l * 0.3,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_concentration_icon.png',
    dependency: Upgrade.burn_damage,
    data: {'max_targets': 1},
    tags: [Tag.burn],
  ),
  Upgrade.burn_damage_extra: UpgradeData(
    maxLevel: 5,
    cost: [50, 150, 300, 500, 750],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.burn_concentration,
    tags: [Tag.burn],
  ),
  Upgrade.burn_damage_extra_for_reduced_tick_rate: UpgradeData(
    maxLevel: 3,
    cost: [50, 200, 400],
    costToken: 'advanced',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_damage_icon.png',
    dependency: Upgrade.burn_damage_extra,
    tags: [Tag.burn],
    data: {
      'damage_increase': {
        'value': (int l) => l * 0.2,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.burn_ticks: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 250, 400, 1000],
    costToken: 'basic',
    value: (int l) => l * 1,
    iconPath: 'assets/sprites/burn_ticks_icon.png',
    dependency: Upgrade.burn_damage_fire_tower,
    tags: [Tag.burn],
  ),
  Upgrade.burn_ticks_extra: UpgradeData(
    maxLevel: 3,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => 2 * l,
    iconPath: 'assets/sprites/burn_ticks_icon.png',
    dependency: Upgrade.burn_ticks,
    tags: [Tag.burn],
  ),
  Upgrade.burn_crit: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    value: (int l) => l,
    iconPath: 'assets/sprites/burn_crit_icon.png',
    dependency: Upgrade.burn_damage,
    keywords: [Keyword.critical_hit],
    data: {
      'damage': {
        'value': 0.15,
        'format': ValueFormat.percentage,
      },
      'burn_crit_chance': {
        'value': (int l) => l * 0.05,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_crit_chance: UpgradeData(
    maxLevel: 3,
    cost: [50, 200, 400],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_crit_icon.png',
    dependency: Upgrade.burn_crit,
    tags: [Tag.burn, Tag.crit],
  ),
  Upgrade.burn_stacking_damage: UpgradeData(
    maxLevel: 3,
    cost: [100, 200, 400],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_stacking_damage_icon.png',
    dependency: Upgrade.burn_damage,
  ),
  Upgrade.burn_spreading: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    value: (int l) => l * 0.075,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/burn_spreading_icon.png',
    dependency: Upgrade.burn_ticks,
    tags: [Tag.burn],
  ),
  Upgrade.burn_spread_chance: UpgradeData(
    maxLevel: 2,
    cost: [50, 250],
    costToken: 'advanced',
    value: (int l) => l * 0.025,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/burn_spreading_icon.png',
    dependency: Upgrade.burn_spreading,
    tags: [Tag.burn],
  ),
  Upgrade.burn_spread_to_burning: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_spreading_icon.png',
    dependency: Upgrade.burn_spread_chance,
    tags: [Tag.burn],
  ),
  Upgrade.burn_pool_apply_burn: UpgradeData(
    maxLevel: 2,
    cost: [50, 150],
    costToken: 'advanced',
    value: (int l) => l * 10,
    iconPath: 'assets/sprites/burn_pool_icon.png',
    dependency: Upgrade.burn_spreading,
    tags: [Tag.burn],
  ),
  Upgrade.burn_pool_apply_burn_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => 10 * l,
    iconPath: 'assets/sprites/burn_pool_icon.png',
    dependency: Upgrade.burn_pool_apply_burn,
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_rate_accelerated_enemies: UpgradeData(
    maxLevel: 4,
    cost: [50, 200, 400, 800],
    costToken: 'advanced',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_rate_icon.png',
    dependency: Upgrade.burn_damage_extra,
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_rate_accelerated_enemies_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'time',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_rate_icon.png',
    dependency: Upgrade.burn_tick_rate_accelerated_enemies,
    tags: [Tag.burn],
  ),
  Upgrade.burn_tick_rate: UpgradeData(
    maxLevel: 3,
    cost: 1,
    costToken: 'time',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/burn_rate_icon.png',
    dependency: Upgrade.burn_damage,
    tags: [Tag.burn],
  ),
  Upgrade.burn_crit_add_tick: UpgradeData(
    maxLevel: 1,
    cost: 150,
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/burn_crit_tick_icon.png',
    dependency: Upgrade.burn_crit,
    tags: [Tag.burn, Tag.crit],
  ),
  Upgrade.fire_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/fire_tower_icon.png',
    dependency: Upgrade.core_health,
    data: {
      'tick_count': BurningStatus.DEFAULT_TICKS,
      'stack_damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
      'reduced_effectiveness_after': 1000,
      'reduced_effectiveness_exponent': 0.75,
      'second_reduced_effectiveness_after': 2500,
      'second_reduced_effectiveness_exponent': 0.55,
    },
    tags: [Tag.burn],
  ),
};
