import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> coreUpgrades = {
  Upgrade.core_health: UpgradeData(
    maxLevel: 5,
    cost: [5, 30, 75, 150, 300],
    costToken: 'basic',
    value: (int l) => l,
    iconPath: 'assets/sprites/health_icon.png',
    dependency: Upgrade.starting_gems,
    tags: [Tag.core],
  ),
  Upgrade.core_health_2: UpgradeData(
    maxLevel: 3,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/health_icon.png',
    dependency: Upgrade.core_health,
    value: (int l) => l * 10,
    tags: [Tag.core],
  ),
  Upgrade.core_health_3: UpgradeData(
    maxLevel: 4,
    cost: [50, 100, 150, 200],
    costToken: 'advanced',
    iconPath: 'assets/sprites/health_icon.png',
    dependency: Upgrade.core_killed_enemy_reward_coins,
    value: (int l) => l * 3,
    tags: [Tag.core],
  ),
  Upgrade.core_burn_pulse: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/burn_pulse_icon.png',
    dependency: Upgrade.core_health_3,
    data: {
      'pulse_cooldown': 3,
    },
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_lost_health_increase_damage: UpgradeData(
    maxLevel: 3,
    cost: [100, 250, 600],
    costToken: 'basic',
    iconPath: 'assets/sprites/lost_health_icon.png',
    dependency: Upgrade.core_health,
    value: (int l) => l * 0.0025,
    valueFormat: ValueFormat.percentage_decimals,
    tags: [Tag.core],
  ),
  Upgrade.core_burn_pulse_damage: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 200, 250],
    costToken: 'advanced',
    iconPath: 'assets/sprites/burn_pulse_damage_icon.png',
    dependency: Upgrade.core_burn_pulse,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_burn_pulse_range: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 200, 250],
    costToken: 'advanced',
    iconPath: 'assets/sprites/burn_pulse_range_icon.png',
    dependency: Upgrade.core_burn_pulse,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_burn_combust: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/core_combust_icon.png',
    dependency: Upgrade.core_burn_pulse_damage,
    keywords: [Keyword.combustion],
    value: (int l) => l * 10,
    data: {
      'combust_ticks': 15,
    },
    tags: [Tag.core, Tag.burn, Tag.combust],
  ),
  Upgrade.core_killed_enemy_reward: UpgradeData(
    maxLevel: 1,
    cost: 100,
    costToken: 'basic',
    iconPath: 'assets/sprites/core_killed_enemy_reward_icon.png',
    dependency: Upgrade.core_health,
    tags: [Tag.core],
  ),
  Upgrade.core_killed_enemy_reward_coins: UpgradeData(
    maxLevel: 2,
    cost: [100, 400],
    costToken: 'basic',
    iconPath: 'assets/sprites/core_killed_enemy_coin_reward_icon.png',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.core_killed_enemy_reward,
    tags: [Tag.core],
  ),
  Upgrade.core_apply_wave_burn: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/core_wave_burn_icon.png',
    dependency: Upgrade.core_burn_pulse_range,
    value: (int l) => l,
    data: {
      'boss_damage': {
        'value': 0.0025,
        'format': ValueFormat.percentage_decimals,
      },
      'regular_damage': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.core, Tag.burn],
  ),
  Upgrade.core_charge: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 200, 250],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    iconPath: 'assets/sprites/core_charge_icon.png',
    dependency: Upgrade.core_burn_pulse_damage,
    tags: [Tag.core, Tag.charge],
    keywords: [Keyword.charge],
  ),
  Upgrade.core_charge_extra: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    value: (int l) => l * 0.25,
    dependency: Upgrade.core_charge,
    iconPath: 'assets/sprites/core_charge_icon.png',
    tags: [Tag.core, Tag.charge],
  ),
  Upgrade.core_heal: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/heal_icon.png',
    dependency: Upgrade.core_lost_health_increase_damage,
    value: (int l) => l * 3,
    data: {
      'increase': {
        'value': 1,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.core_heal_extra: UpgradeData(
    maxLevel: 2,
    cost: [50, 150],
    costToken: 'advanced',
    iconPath: 'assets/sprites/heal_more_icon.png',
    dependency: Upgrade.core_heal,
    value: (int l) => l,
  ),
};
