import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> economyUpgrades = {
  Upgrade.starting_gems: UpgradeData(
    maxLevel: 5,
    cost: [3, 10, 20, 40, 100],
    costToken: 'basic',
    value: (int l) => l * 5,
    iconPath: 'assets/sprites/starting_gems_icon.png',
    dependency: Upgrade.arrow_tower_unlock,
    tags: [Tag.economy],
  ),
  Upgrade.starting_gems_2: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 200, 250],
    costToken: 'advanced',
    value: (int l) => l * 10,
    iconPath: 'assets/sprites/starting_gems_icon.png',
    dependency: Upgrade.gem_convert,
    tags: [Tag.economy],
  ),
  Upgrade.gem_convert: UpgradeData(
    maxLevel: 5,
    cost: [10, 100, 200, 400, 800],
    costToken: 'basic',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/gem_convert_icon.png',
    dependency: Upgrade.gem_shot,
    tags: [Tag.economy],
  ),
  Upgrade.gem_drops: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    value: (int l) => l,
    iconPath: 'assets/sprites/gem_drops_icon.png',
    dependency: Upgrade.boss_damage_taken_basic_token_increase,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.economy],
  ),
  Upgrade.early_spawn: UpgradeData(
    maxLevel: 1,
    cost: 250,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/early_spawn_icon.png',
    value: (int l) => l,
    dependency: Upgrade.tower_upgrade_unlock,
    data: {
      'gem': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.economy],
  ),
  Upgrade.early_spawn_gem_bonus: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 200, 400, 800],
    costToken: 'basic',
    iconPath: 'assets/sprites/early_spawn_gem_bonus_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.basic_token_drops,
    tags: [Tag.economy],
  ),
  Upgrade.early_spawn_charge: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 200, 250],
    costToken: 'advanced',
    iconPath: 'assets/sprites/early_spawn_charge_icon.png',
    value: (int l) => l * 0.5,
    dependency: Upgrade.early_spawn_gem_bonus,
    tags: [Tag.charge],
    keywords: [Keyword.charge],
  ),
  Upgrade.early_spawn_charge_extra: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/early_spawn_charge_icon.png',
    value: (int l) => l * 1.5,
    dependency: Upgrade.early_spawn_charge,
    tags: [Tag.charge],
    keywords: [Keyword.charge],
  ),
  Upgrade.accelerated_enemy_basic_token_bonus: UpgradeData(
    maxLevel: 2,
    cost: [100, 200],
    costToken: 'advanced',
    iconPath: 'assets/sprites/early_spawn_basic_token_bonus_icon.png',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.early_spawn_gem_bonus,
    tags: [Tag.economy],
  ),
  Upgrade.basic_token_drops: UpgradeData(
    maxLevel: 5,
    cost: [15, 30, 50, 75, 115],
    costToken: 'basic',
    iconPath: 'assets/sprites/green_token_drops_icon.png',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.starting_gems,
    tags: [Tag.economy],
  ),
  Upgrade.gem_cannon: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    value: (int l) => l,
    iconPath: 'assets/sprites/gem_cannon_icon.png',
    dependency: Upgrade.starting_gems,
    data: {
      'damage_range': '10-20',
    },
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_auto_shoot: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    defaultUnlockedOnMobile: true,
    iconPath: 'assets/sprites/auto_shoot_icon.png',
    value: (int l) => l,
    dependency: Upgrade.gem_cannon,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_shot: UpgradeData(
    maxLevel: 5,
    cost: [50, 75, 125, 200, 350],
    costToken: 'basic',
    iconPath: 'assets/sprites/gem_shot_icon.png',
    dependency: Upgrade.gem_drops,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_damage: UpgradeData(
    maxLevel: 10,
    cost: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    costToken: 'basic',
    iconPath: 'assets/sprites/gem_cannon_damage_icon.png',
    value: (int l) => l * 5,
    dependency: Upgrade.gem_cannon,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_damage_extra: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 200, 400, 800],
    costToken: 'advanced',
    value: (int l) => l * 5,
    dependency: Upgrade.gem_cannon_crit_chance,
    iconPath: 'assets/sprites/gem_cannon_damage_icon.png',
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_fire_rate: UpgradeData(
    maxLevel: 2,
    cost: [1, 2],
    costToken: 'time',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/gem_cannon_fire_rate.png',
    dependency: Upgrade.gem_cannon,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_shot_reimbursement_chance: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/gem_cannon_reimburse.png',
    dependency: Upgrade.gem_cannon_damage,
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_crit_chance: UpgradeData(
    maxLevel: 3,
    iconPath: 'assets/sprites/gem_cannon_crit_icon.png',
    cost: [100, 200, 400],
    costToken: 'basic',
    dependency: Upgrade.gem_cannon_damage,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    keywords: [Keyword.critical_hit],
    tags: [Tag.coin_cannon, Tag.crit],
  ),
  Upgrade.auto_collect_gems: UpgradeData(
    maxLevel: 1,
    cost: 5000,
    value: (int l) => l,
    isMilestone: true,
    defaultUnlockedOnMobile: true,
    costToken: 'basic',
    iconPath: 'assets/sprites/auto_collect_gems_icon.png',
    dependency: Upgrade.tower_upgrade_unlock,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/unlock_bank_tower.png',
    dependency: Upgrade.basic_token_drops,
    data: {
      'chance_to_spawn_coin': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_chance_to_spawn_coin: UpgradeData(
    maxLevel: 5,
    cost: [25, 50, 100, 200, 400],
    costToken: 'basic',
    iconPath: 'assets/sprites/bank_tower_coin_icon.png',
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.bank_tower_unlock,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_pool: UpgradeData(
    maxLevel: 1,
    cost: 250,
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_pool_icon.png',
    dependency: Upgrade.bank_tower_chance_to_spawn_coin,
    keywords: [Keyword.pool],
    tags: [Tag.economy, Tag.pool],
  ),
  Upgrade.bank_tower_tokens: UpgradeData(
    maxLevel: 1,
    cost: 100,
    costToken: 'advanced',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_token_icon.png',
    dependency: Upgrade.bank_tower_chance_to_spawn_coin,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_basic_tokens_multiplier: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l * 1.0,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/bank_tower_token_multiplier_icon.png',
    dependency: Upgrade.bank_tower_tokens,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_damage: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    value: (int l) => l * 0.015,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/bank_tower_damage_icon.png',
    dependency: Upgrade.bank_tower_tokens,
    tags: [Tag.economy],
    data: {
      'min_damage': 25,
    },
  ),
  Upgrade.bank_tower_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: [50, 250],
    costToken: 'advanced',
    value: (int l) => l * 0.005,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/bank_tower_damage_icon.png',
    dependency: Upgrade.bank_tower_damage,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_accelerated_enemies: UpgradeData(
    maxLevel: 1,
    cost: 2,
    costToken: 'time',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_accelerated_coin_icon.png',
    dependency: Upgrade.bank_tower_tokens,
    tags: [Tag.economy],
  ),
  Upgrade.gem_cannon_damage_expensive: UpgradeData(
    maxLevel: 2,
    cost: [500, 1500],
    costToken: 'basic',
    iconPath: 'assets/sprites/gem_cannon_expensive_damage_icon.png',
    dependency: Upgrade.gem_cannon_damage,
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    data: {
      'cost_increase': {
        'value': (int l) => l,
        'format': ValueFormat.number,
      },
    },
    tags: [Tag.coin_cannon],
  ),
  Upgrade.gem_cannon_damage_expensive_extra: UpgradeData(
    maxLevel: 2,
    cost: [250, 500],
    costToken: 'advanced',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.gem_cannon_damage_expensive,
    iconPath: 'assets/sprites/gem_cannon_expensive_damage_icon.png',
    tags: [Tag.coin_cannon],
    data: {
      'cost_increase': {
        'value': (int l) => l,
        'format': ValueFormat.number,
      },
    },
  ),
  Upgrade.economy_damage_increase_by_coins: UpgradeData(
    maxLevel: 3,
    cost: [50, 200, 400],
    costToken: 'advanced',
    value: (int l) => l * 0.0005,
    valueFormat: ValueFormat.percentage_decimals,
    iconPath: 'assets/sprites/coins_damage_icon.png',
    dependency: Upgrade.gem_shot,
    tags: [Tag.economy],
    data: {
      'max_damage_increase': {
        'value': 0.3,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.economy_gem_interest: UpgradeData(
    maxLevel: 3,
    cost: [100, 300, 500],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.starting_gems_2,
    iconPath: 'assets/sprites/interest_icon.png',
    tags: [Tag.economy],
  ),
  Upgrade.economy_enemy_defeat_upgrade_discount: UpgradeData(
    maxLevel: 3,
    cost: [250, 500, 750],
    costToken: 'advanced',
    value: (int l) => l * 0.0025,
    valueFormat: ValueFormat.percentage_decimals,
    dependency: Upgrade.economy_damage_increase_by_coins,
    iconPath: 'assets/sprites/defeat_upgrade_discount_icon.png',
    tags: [Tag.economy],
  ),
  Upgrade.economy_uncapped_levels: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l,
    dependency: Upgrade.economy_enemy_defeat_upgrade_discount,
    iconPath: 'assets/sprites/uncapped_levels_icon.png',
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_number_coins: UpgradeData(
    maxLevel: 2,
    cost: [1, 2],
    costToken: 'challenge',
    value: (int l) => l,
    iconPath: 'assets/sprites/bank_tower_coin_icon.png',
    dependency: Upgrade.bank_tower_chance_to_spawn_coin,
    tags: [Tag.economy],
  ),
  Upgrade.boss_defeat_partial_token: UpgradeData(
    maxLevel: 1,
    cost: 50,
    costToken: 'basic',
    iconPath: 'assets/sprites/boss_defeat_partial_token.png',
    dependency: Upgrade.basic_token_drops,
    data: {
      'drop_coin_per_health': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.economy],
  ),
  Upgrade.boss_damage_taken_basic_token_increase: UpgradeData(
    maxLevel: 3,
    cost: [100, 200, 300],
    costToken: 'basic',
    iconPath: 'assets/sprites/boss_defeat_partial_token_increase.png',
    dependency: Upgrade.boss_defeat_partial_token,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.economy],
  ),
  Upgrade.bank_tower_add_vulnerable: UpgradeData(
    maxLevel: 2,
    cost: [500, 750],
    costToken: 'basic',
    iconPath: 'assets/sprites/bank_tower_vulnerable_icon.png',
    value: (int l) => l * 0.5,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.bank_tower_unlock,
    keywords: [Keyword.vulnerable],
    data: {
      'vulnerable_duration': 1.0,
      'vulnerable_damage':
          ((VulnerableStatus.BASE_DAMAGE_MULTIPLIER - 1.0) * 100).round(),
    },
    tags: [Tag.economy, Tag.vulnerable],
  ),
  Upgrade.bank_tower_vulnerable_duration: UpgradeData(
    maxLevel: 3,
    cost: [250, 500, 750],
    costToken: 'basic',
    iconPath: 'assets/sprites/bank_tower_vulnerable_duration_icon.png',
    value: (int l) => l * 1.0,
    dependency: Upgrade.bank_tower_add_vulnerable,
    tags: [Tag.economy],
  ),
};
