import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> explosiveUpgrades = {
  Upgrade.explosive_grunts: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/explosion_icon.png',
    value: (int l) => l,
    dependency: Upgrade.arrow_tower_damage,
    data: {
      'base_chance': 0.2,
      'chance': {
        'value': 0.25,
        'format': ValueFormat.percentage,
      },
      'damage': {
        'value': 0.15,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_grunts_chance: UpgradeData(
    maxLevel: 3,
    cost: [25, 150, 500],
    costToken: 'basic',
    iconPath: 'assets/sprites/explosion_chance_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_grunts,
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_runners_chance: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/explosive_runners_icon.png',
    value: (int l) => l * 0.15,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_grunts_chance,
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_damage: UpgradeData(
    maxLevel: 7,
    cost: [30, 90, 220, 450, 1000, 1500, 2000],
    costToken: 'basic',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/explosion_damage_icon.png',
    dependency: Upgrade.explosive_grunts,
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_damage_2: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 250, 400],
    costToken: 'advanced',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosion_range_increase,
    iconPath: 'assets/sprites/explosion_damage_icon.png',
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_bosses: UpgradeData(
    maxLevel: 3,
    cost: [50, 250, 750],
    costToken: 'basic',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_bosses_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_elites,
    data: {
      'damage': {
        'value': 1.0,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_elites: UpgradeData(
    maxLevel: 3,
    cost: [50, 250, 750],
    costToken: 'basic',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_elites_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_damage,
    data: {
      'damage': {
        'value': 0.5,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.explosive],
  ),
  Upgrade.explosive_bosses_2: UpgradeData(
    maxLevel: 3,
    cost: [50, 100, 150],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_bosses_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_bosses,
  ),
  Upgrade.explosive_elites_2: UpgradeData(
    maxLevel: 3,
    cost: [50, 100, 150],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/explosive_elites_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_elites,
  ),
  Upgrade.explosion_fireball: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_icon.png',
    dependency: Upgrade.explosive_damage,
    tags: [Tag.explosive, Tag.burn],
    data: {
      'burn_damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
      'explosion_damage': {
        'value': 0.1,
        'format': ValueFormat.percentage,
      },
    },
  ),
  Upgrade.explosion_fireball_chance: UpgradeData(
    maxLevel: 5,
    cost: [150, 300, 500, 1000, 1500],
    costToken: 'basic',
    value: (int l) => l * 0.03,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_icon.png',
    dependency: Upgrade.explosion_fireball,
    tags: [Tag.explosive, Tag.burn],
  ),
  Upgrade.explosion_fireball_burn_damage: UpgradeData(
    maxLevel: 5,
    cost: [50, 125, 250, 375, 500],
    costToken: 'advanced',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_damage_icon.png',
    dependency: Upgrade.explosion_fireball_chance,
  ),
  Upgrade.explosion_fireball_explosion_damage: UpgradeData(
    maxLevel: 5,
    cost: [50, 125, 250, 375, 500],
    costToken: 'advanced',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/fireball_damage_icon.png',
    dependency: Upgrade.explosion_fireball_chance,
  ),
  Upgrade.explosion_fireball_double_chance: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/double_fireball_icon.png',
    dependency: Upgrade.explosion_fireball_chance,
  ),
  Upgrade.explosion_range_increase: UpgradeData(
    maxLevel: 5,
    cost: [50, 200, 400, 800, 1500],
    costToken: 'advanced',
    value: (int l) => l * 0.1,
    iconPath: 'assets/sprites/explosion_range_icon.png',
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.explosive_damage,
    tags: [Tag.explosive],
  ),
  Upgrade.explosion_tower_charge: UpgradeData(
    maxLevel: 4,
    cost: [75, 150, 300, 750],
    costToken: 'advanced',
    value: (int l) => l * 0.15,
    iconPath: 'assets/sprites/explosion_charge_icon.png',
    dependency: Upgrade.explosive_damage_2,
    tags: [Tag.explosive],
    keywords: [Keyword.charge],
  ),
  Upgrade.explosion_tower_charge_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'time',
    value: (int l) => l * 0.15,
    iconPath: 'assets/sprites/explosion_charge_icon.png',
    dependency: Upgrade.explosion_tower_charge,
    tags: [Tag.explosive],
  ),
  Upgrade.explosion_chance_to_create_pool: UpgradeData(
    maxLevel: 3,
    cost: [50, 150, 300],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/explosive_pool_icon.png',
    dependency: Upgrade.explosion_tower_charge,
    tags: [Tag.explosive],
    keywords: [Keyword.pool],
  ),
};
