import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> lightningUpgrades = {
  Upgrade.lightning_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    dependency: Upgrade.arrow_tower_fire_rate,
    iconPath: 'assets/sprites/lightning_tower_icon.png',
    value: 1,
    data: {
      'jump_damage_reduction': {
        'value': 0.3,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_spread_status: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/lightning_status_link_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_jumps: UpgradeData(
    maxLevel: 3,
    cost: [25, 250, 500],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_jumps_icon.png',
    dependency: Upgrade.lightning_tower_unlock,
    value: (int l) => l,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_extra_jumps: UpgradeData(
    maxLevel: 3,
    cost: [50, 150, 300],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_jumps_icon.png',
    dependency: Upgrade.lightning_tower_jumps,
    value: (int l) => l,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_damage: UpgradeData(
    maxLevel: 8,
    cost: [50, 150, 150, 200, 250, 500, 750, 1000],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_damage_icon.png',
    dependency: Upgrade.lightning_tower_jumps,
    value: (int l) => l * 5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_damage_extra: UpgradeData(
    maxLevel: 8,
    cost: [50, 75, 100, 200, 500, 750, 1000, 1500],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_damage_icon.png',
    dependency: Upgrade.lightning_tower_damage,
    value: (int l) => l * 5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_speed: UpgradeData(
    maxLevel: 5,
    cost: [25, 50, 100, 500, 1000],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_rate_icon.png',
    dependency: Upgrade.lightning_tower_unlock,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_crit_chance: UpgradeData(
    maxLevel: 6,
    cost: [100, 200, 400, 800, 1200, 1600],
    costToken: 'basic',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/lightning_crit_chance_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    tags: [Tag.lightning, Tag.crit],
  ),
  Upgrade.lightning_tower_crit_charge: UpgradeData(
    maxLevel: 3,
    cost: [50, 200, 500],
    costToken: 'advanced',
    value: (int l) => l * 0.05,
    iconPath: 'assets/sprites/lightning_crit_charge_icon.png',
    dependency: Upgrade.lightning_tower_crit_chance,
    keywords: [Keyword.charge],
    tags: [Tag.charge, Tag.lightning],
  ),
  Upgrade.lightning_tower_charge_extra_jumps: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/lightning_jumps_icon.png',
    dependency: Upgrade.lightning_tower_crit_charge,
    value: (int l) => l,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_extra_speed: UpgradeData(
    maxLevel: 3,
    cost: [1, 2, 3],
    costToken: 'time',
    iconPath: 'assets/sprites/lightning_rate_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_overkill_damage: UpgradeData(
    maxLevel: 3,
    cost: [50, 250, 500],
    costToken: 'advanced',
    iconPath: 'assets/sprites/overkill_icon.png',
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.lightning_tower_unlock,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_overkill_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/overkill_icon.png',
    dependency: Upgrade.lightning_tower_overkill_damage,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_overkill_retrigger_chance: UpgradeData(
    maxLevel: 2,
    cost: [250, 500],
    costToken: 'advanced',
    iconPath: 'assets/sprites/overkill_retrigger_icon.png',
    dependency: Upgrade.lightning_tower_overkill_damage_extra,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_jump_damage_reduction: UpgradeData(
    maxLevel: 3,
    cost: [100, 250, 1000],
    costToken: 'basic',
    iconPath: 'assets/sprites/lightning_jump_damage_icon.png',
    dependency: Upgrade.lightning_tower_speed,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_chance_to_jump_again: UpgradeData(
    maxLevel: 3,
    cost: [250, 500, 750],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_accelerated_jumps_icon.png',
    dependency: Upgrade.lightning_tower_jump_damage_reduction,
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_chance_to_jump_again_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/lightning_accelerated_jumps_icon.png',
    dependency: Upgrade.lightning_tower_chance_to_jump_again,
    value: (int l) => l * 0.1,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_apply_shock: UpgradeData(
    maxLevel: 1,
    cost: 200,
    costToken: 'basic',
    iconPath: 'assets/sprites/shock_icon.png',
    dependency: Upgrade.lightning_tower_damage,
    value: 0.75,
    data: {
      'shock_count': 5,
    },
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_stun_increase_damage: UpgradeData(
    maxLevel: 3,
    cost: [100, 250, 500],
    costToken: 'advanced',
    iconPath: 'assets/sprites/shock_icon.png',
    dependency: Upgrade.lightning_tower_apply_shock,
    value: (int l) => 0.1 * l,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_stun_increase_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/shock_icon.png',
    dependency: Upgrade.lightning_tower_stun_increase_damage,
    value: (int l) => 0.25 * l,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_shock_stun_duration: UpgradeData(
    maxLevel: 2,
    cost: [100, 250],
    costToken: 'basic',
    iconPath: 'assets/sprites/discharge_duration_icon.png',
    dependency: Upgrade.lightning_tower_apply_shock,
    value: (int l) => l * 0.5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_shock_stun_duration_extra: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/discharge_duration_icon.png',
    dependency: Upgrade.lightning_tower_shock_stun_duration,
    value: (int l) => l * 0.5,
    tags: [Tag.lightning],
  ),
  Upgrade.lightning_tower_discharge_combust: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/discharge_combust_icon.png',
    dependency: Upgrade.lightning_tower_apply_shock,
    keywords: [Keyword.combustion],
    data: {
      'combust_ticks': 50,
    },
    tags: [Tag.lightning, Tag.explosive],
  ),
  Upgrade.lightning_tower_jump_range: UpgradeData(
    maxLevel: 3,
    cost: [50, 100, 200],
    costToken: 'advanced',
    iconPath: 'assets/sprites/lightning_jump_range_icon.png',
    dependency: Upgrade.lightning_tower_jump_damage_reduction,
    value: (int l) => l * 0.2,
    valueFormat: ValueFormat.percentage,
    tags: [Tag.lightning],
  ),
  Upgrade.status_effect_count_increase_damage: UpgradeData(
    maxLevel: 3,
    cost: [50, 200, 400],
    costToken: 'advanced',
    value: (int l) => l * 0.01,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/status_count_damage_icon.png',
    dependency: Upgrade.lightning_tower_spread_status,
    tags: [],
  ),
  Upgrade.status_effect_count_increase_damage_extra: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'challenge',
    value: (int l) => l * 0.01,
    valueFormat: ValueFormat.percentage,
    iconPath: 'assets/sprites/status_count_damage_icon.png',
    dependency: Upgrade.status_effect_count_increase_damage,
    tags: [],
  ),
};
