import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> miscUpgrades = {
  Upgrade.tower_upgrade_unlock: UpgradeData(
    maxLevel: 1,
    cost: 10,
    costToken: 'basic',
    isMilestone: true,
    dependency: Upgrade.arrow_tower_unlock,
    iconPath: 'assets/sprites/upgrade_icon.png',
    tags: [Tag.core],
  ),
  Upgrade.tower_demolish_unlock: UpgradeData(
    maxLevel: 1,
    cost: 100,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/demolish_icon.png',
    dependency: Upgrade.tower_upgrade_unlock,
    data: {
      'full_refund': {
        'value': 1.0,
        'format': ValueFormat.percentage,
      },
      'partial_refund': {
        'value': 0.5,
        'format': ValueFormat.percentage,
      },
    },
    tags: [Tag.misc],
  ),
  Upgrade.auto_start_wave: UpgradeData(
    maxLevel: 1,
    isMilestone: true,
    cost: 3500,
    costToken: 'basic',
    iconPath: 'assets/sprites/auto_start_wave_icon.png',
    value: (int l) => l,
    dependency: Upgrade.tower_upgrade_auto,
    tags: [Tag.misc],
  ),
  Upgrade.time_challenge_unlock: UpgradeData(
    maxLevel: 1,
    cost: 500,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/time_challenge_icon.png',
    value: (int l) => l,
    dependency: Upgrade.early_spawn,
    tags: [Tag.core],
  ),
  Upgrade.tower_upgrade_auto: UpgradeData(
    maxLevel: 1,
    cost: 1250,
    isMilestone: true,
    costToken: 'basic',
    iconPath: 'assets/sprites/auto_upgrade_icon.png',
    dependency: Upgrade.tower_upgrade_unlock,
    tags: [Tag.core],
  ),
  Upgrade.level_challenge_unlock: UpgradeData(
    maxLevel: 1,
    isMilestone: true,
    cost: 2500,
    value: (int l) => l,
    costToken: 'basic',
    iconPath: 'assets/sprites/level_challenge_icon.png',
    dependency: Upgrade.time_challenge_unlock,
    tags: [Tag.core],
  ),
  Upgrade.demolish_unrestricted: UpgradeData(
    maxLevel: 1,
    cost: 250,
    costToken: 'basic',
    iconPath: 'assets/sprites/demolish_unrestricted_icon.png',
    value: (int l) => l,
    dependency: Upgrade.gem_drops,
  ),
  Upgrade.demolish_refund_amount: UpgradeData(
    maxLevel: 5,
    cost: [100, 200, 300, 400, 500],
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    costToken: 'basic',
    iconPath: 'assets/sprites/demolish_refund_amount_icon.png',
    dependency: Upgrade.demolish_unrestricted,
  ),
  Upgrade.demolish_refund_amount_2: UpgradeData(
    maxLevel: 1,
    cost: 1,
    value: (int l) => l * 0.25,
    valueFormat: ValueFormat.percentage,
    costToken: 'challenge',
    iconPath: 'assets/sprites/demolish_refund_amount_icon.png',
    dependency: Upgrade.demolish_refund_amount,
  ),
  Upgrade.demolish_explosion: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 200, 250],
    costToken: 'advanced',
    iconPath: 'assets/sprites/demolish_explosion_icon.png',
    value: (int l) => l * 2.0,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.demolish_refund_amount,
  ),
  Upgrade.build_presets_unlock: UpgradeData(
    maxLevel: 1,
    cost: 2500,
    costToken: 'basic',
    isMilestone: true,
    iconPath: 'assets/sprites/build_presets_icon.png',
    dependency: Upgrade.level_challenge_unlock,
    tags: [Tag.misc],
  ),
};
