import '../upgrade_data.dart';
import '../upgrade_ids.dart';

final Map<Upgrade, UpgradeData> slowUpgrades = {
  Upgrade.slow_tower_unlock: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/slow_tower_icon.png',
    dependency: Upgrade.arrow_tower_unlock,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_damage_link: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/damage_link_icon.png',
    value: (int l) => l * 0.3,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_fire_rate,
    data: {
      'damage': {
        'value': 0.15,
        'format': ValueFormat.percentage,
      },
      'reduced_effectiveness_after': 10,
      'damage_reduction_multiplier': 0.65,
    },
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_damage_link_increase: UpgradeData(
    maxLevel: 5,
    cost: [75, 150, 350, 650, 1250],
    costToken: 'basic',
    iconPath: 'assets/sprites/damage_link_increase_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_damage_link,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_damage_link_share_sources: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/damage_link_share_sources_icon.png',
    dependency: Upgrade.slow_tower_damage_link,
    tags: [Tag.slow],
  ),
  Upgrade.slow_vulnerable: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 200, 400, 800],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_damage_multiplier.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_fire_rate,
    data: {
      'vulnerable_damage':
          ((VulnerableStatus.BASE_DAMAGE_MULTIPLIER - 1.0) * 100).round(),
    },
    keywords: [Keyword.vulnerable],
    tags: [Tag.slow, Tag.vulnerable],
  ),
  Upgrade.slow_amount: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 200, 400, 800],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_icon.png',
    value: (int l) => l * 0.02,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_unlock,
    tags: [Tag.slow],
  ),
  Upgrade.slow_duration: UpgradeData(
    maxLevel: 4,
    cost: [100, 200, 300, 400],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_duration_icon.png',
    value: (int l) => l * 0.05,
    dependency: Upgrade.slow_amount,
    tags: [Tag.slow],
  ),
  Upgrade.slow_duration_2: UpgradeData(
    maxLevel: 2,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/slow_duration_icon.png',
    value: (int l) => l * 0.15,
    dependency: Upgrade.slow_duration,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_fire_rate: UpgradeData(
    maxLevel: 3,
    cost: [25, 75, 200],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_tower_fire_rate_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_unlock,
    tags: [Tag.slow],
  ),
  Upgrade.slow_tower_charge_buff: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'star',
    iconPath: 'assets/sprites/slow_tower_charge_buff_icon.png',
    value: (int l) => l * 0.25,
    dependency: Upgrade.slow_tower_fire_rate,
    keywords: [Keyword.charge],
    tags: [Tag.charge],
  ),
  Upgrade.charge_amount: UpgradeData(
    maxLevel: 3,
    cost: [200, 400, 800],
    costToken: 'basic',
    iconPath: 'assets/sprites/slow_tower_charge_buff_icon.png',
    value: (int l) => l * 0.05,
    dependency: Upgrade.slow_tower_charge_buff,
    tags: [Tag.charge],
  ),
  Upgrade.charge_amount_2: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'time',
    iconPath: 'assets/sprites/slow_tower_charge_buff_icon.png',
    value: (int l) => l * 0.1,
    dependency: Upgrade.charge_amount,
    tags: [Tag.charge],
  ),
  Upgrade.charge_damage_bonus: UpgradeData(
    maxLevel: 5,
    cost: [50, 100, 150, 250, 400],
    costToken: 'advanced',
    iconPath: 'assets/sprites/charge_damage_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_tower_charge_buff,
    tags: [Tag.charge],
  ),
  Upgrade.slow_damage_bonus: UpgradeData(
    maxLevel: 5,
    cost: [150, 250, 400, 650, 1000],
    costToken: 'advanced',
    iconPath: 'assets/sprites/slow_damage_bonus_icon.png',
    value: (int l) => l * 0.02,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_vulnerable,
    tags: [Tag.slow],
  ),
  Upgrade.charge_damage_stacking: UpgradeData(
    maxLevel: 1,
    cost: 1,
    costToken: 'challenge',
    iconPath: 'assets/sprites/charge_damage_stacking_icon.png',
    value: (int l) => l * 15,
    dependency: Upgrade.charge_damage_bonus,
    tags: [Tag.charge],
  ),
  Upgrade.slow_zone: UpgradeData(
    maxLevel: 3,
    cost: [50, 100, 150],
    costToken: 'advanced',
    iconPath: 'assets/sprites/slow_zone_icon.png',
    value: (int l) => l * 0.05,
    valueFormat: ValueFormat.percentage,
    dependency: Upgrade.slow_duration,
    data: {
      'duration': 5.0,
    },
    tags: [Tag.slow, Tag.pool],
    keywords: [Keyword.pool],
  ),
};
